<template>
    <a-modal
        :open="visible"
        :centered="true"
        :maskClosable="false"
        :title="$t('common.print_invoice')"
        width="480px"
        @cancel="onClose"
    >
        <div id="dmart-invoice">
            <div class="os-wrap" v-if="order && order.xid">

                <!-- ── HEADER ── -->
                <div class="os-header">
                    <!-- Logo / bag icon -->
                    <div class="os-logo">
                        <img
                            v-if="selectedWarehouse.logo_url"
                            :src="selectedWarehouse.logo_url"
                            class="os-logo-img"
                            alt="logo"
                        />
                        <svg v-else width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <rect x="3" y="11" width="24" height="17" rx="2" stroke="#111" stroke-width="1.6" fill="none"/>
                            <path d="M10 11V9a5 5 0 0 1 10 0v2" stroke="#111" stroke-width="1.6" fill="none" stroke-linecap="round"/>
                            <circle cx="15" cy="19.5" r="2" fill="#111"/>
                        </svg>
                    </div>
                    <h1 class="os-name">{{ selectedWarehouse.name }}</h1>
                    <p class="os-addr">{{ selectedWarehouse.address }}</p>
                    <p class="os-contact">
                        <span v-if="selectedWarehouse.phone">Phone: {{ selectedWarehouse.phone }}</span>
                        <span v-if="selectedWarehouse.phone && selectedWarehouse.email"> | </span>
                        <span v-if="selectedWarehouse.email">Email: {{ selectedWarehouse.email }}</span>
                    </p>
                </div>

                <hr class="os-hr" />

                <!-- ── INVOICE META ── -->
                <div class="os-meta">
                    <div class="os-meta-left">
                        <div class="os-mrow"><span class="os-ml">Invoice No.</span><span class="os-mv">: {{ order.invoice_number }}</span></div>
                        <div class="os-mrow"><span class="os-ml">Date</span><span class="os-mv">: {{ formatDate(order.order_date) }}</span></div>
                        <div class="os-mrow"><span class="os-ml">Time</span><span class="os-mv">: {{ getTime(order.order_date) }}</span></div>
                    </div>
                    <div class="os-meta-right">
                        <div class="os-mrow os-mr-row"><span class="os-ml">Generated by:</span><span class="os-mv">{{ order.staff_member?.name || 'Admin' }}</span></div>
                        
                    </div>
                </div>

                <hr class="os-hr" />

                <!-- ── CUSTOMER DETAILS ── -->
                <p class="os-sec-title">CUSTOMER DETAILS :</p>
                <div class="os-customer">
                    <div class="os-crow"><span class="os-cl">Name</span><span class="os-cv">: {{ customer.name }}</span></div>
                    <div class="os-crow" v-if="customer.phone"><span class="os-cl">Mob</span><span class="os-cv">: {{ customer.phone }}</span></div>
                    <div class="os-crow" v-if="customer.address"><span class="os-cl">Address</span><span class="os-cv">: {{ customer.address }}</span></div>
                </div>

                <!-- ── ITEMS TABLE ── -->
                <table class="os-table">
                    <thead>
                        <tr class="os-thead-tr">
                            <th class="os-th os-tc" style="width:8%">NO.</th>
                            <th class="os-th os-tl" style="width:42%">ITEM<br>DESCRIPTION</th>
                            <th class="os-th os-tc" style="width:10%">QTY</th>
                            <th class="os-th os-tr" style="width:15%">RATE</th>
                            <th class="os-th os-tc" style="width:10%">GST</th>
                            <th class="os-th os-tr" style="width:15%">AMOUNT</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(item, index) in order.items" :key="item.xid" class="os-item-tr">
                            <td class="os-td os-tc">{{ index + 1 }}</td>
                            <td class="os-td os-tl">{{ item.product?.name }}</td>
                            <td class="os-td os-tc">{{ item.quantity }}</td>
                            <td class="os-td os-tr">{{ formatAmountCurrency(item.unit_price) }}</td>
                            <td class="os-td os-tc">{{ getTaxRate(item) }}%</td>
                            <td class="os-td os-tr">{{ formatAmountCurrency(item.subtotal) }}</td>
                        </tr>
                    </tbody>
                </table>

                <hr class="os-hr-thin" />

                <!-- ── TAX TOTALS ── -->
                <div class="os-totals">
                    <div class="os-trow"><span>SUBTOTAL</span><span>{{ formatAmountCurrency(taxableAmount) }}</span></div>
                    <div class="os-trow gst-cgst" v-if="itemGSTDetails.cgst > 0"><span>CGST @ {{ cgstRate }}%</span><span>{{ formatAmountCurrency(cgstAmount) }}</span></div>
                    <div class="os-trow gst-sgst" v-if="itemGSTDetails.sgst > 0"><span>SGST @ {{ sgstRate }}%</span><span>{{ formatAmountCurrency(sgstAmount) }}</span></div>
                    <div class="os-trow gst-igst" v-if="itemGSTDetails.igst > 0"><span>IGST @ {{ igstRate }}%</span><span>{{ formatAmountCurrency(igstAmount) }}</span></div>
                    <div class="os-trow total-tax" v-if="totalTax > 0"><span>TOTAL TAX</span><span>{{ formatAmountCurrency(totalTax) }}</span></div>
                </div>

                <hr class="os-hr-thin" />

                <!-- ── NET AMOUNT ── -->
                <div class="os-net">
                    <span>NET AMOUNT</span>
                    <span>{{ formatAmountCurrency(order.total) }}</span>
                </div>

                <hr class="os-hr-thin" />

                <!-- ── PAID / DUE ── -->
                <div class="os-totals">
                    <div class="os-trow"><span>PAID AMOUNT</span><span>{{ formatAmountCurrency(paidAmount) }}</span></div>
                    <div class="os-trow"><span>DUE AMOUNT</span><span>{{ formatAmountCurrency(dueAmount) }}</span></div>
                </div>

                <hr class="os-hr-thin" />

                <!-- ── BANK DETAILS ── -->
                <p class="os-sec-title">BANK DETAIL :</p>
                <div class="os-bank">
                    <div class="os-brow"><span class="os-bl">A/c No</span><span class="os-bv">: {{ selectedWarehouse.bank_account_no || selectedWarehouse.account_number || '18650200016691' }}</span></div>
                    <div class="os-brow"><span class="os-bl">Bank</span><span class="os-bv">: {{ selectedWarehouse.bank_name || 'THE FEDERAL BANK' }}</span></div>
                    <div class="os-brow"><span class="os-bl">Branch</span><span class="os-bv">: {{ selectedWarehouse.bank_branch || selectedWarehouse.branch_name || 'SURAT VARACHHA' }}</span></div>
                    <div class="os-brow"><span class="os-bl">IFSC</span><span class="os-bv">: {{ selectedWarehouse.ifsc_code || 'FDRL0001855' }}</span></div>
                </div>

                <hr class="os-hr-thin" />

                <!-- ── DESCRIPTION (if provided) ── -->
                <div v-if="description && description.trim()" class="os-description">
                    <p class="os-sec-title">ADDITIONAL DESCRIPTION :</p>
                    <p class="os-desc-text">{{ description }}</p>
                </div>

                <hr v-if="description && description.trim()" class="os-hr-thin" />

                <!-- ── TERMS ── -->
                <p class="os-sec-title">TERMS OF SALES :</p>
                <p class="os-terms">{{ selectedWarehouse.terms_condition || selectedWarehouse.invoice_terms || 'Goods once sold will be taken back or exchanged within 10 Days.' }}</p>

                <hr class="os-hr-thin" />

                <!-- ── SIGNATURE ── -->
                <div class="os-sig">
                    <p class="os-for">For : <strong>{{ selectedWarehouse.name?.toUpperCase() }}</strong></p>
                    <div class="os-sig-gap"></div>
                    <p class="os-auth">Authorised Signatory</p>
                    <p class="os-store-sig">{{ selectedWarehouse.name }}</p>
                </div>

                <!-- ── FOOTER ── -->
                <div class="os-footer">
                    <div class="os-thank-you">Thank You For Shopping With Us. Please Come Again</div>
                </div>

            </div>
        </div>

        <template #footer>
            <div class="os-modal-footer">
                <div class="os-layout-pick">
                    <a-space>
                        <span>Print Layout:</span>
                        <a-select v-model:value="selectedPrintLayout" style="width:140px;" @change="onPrintLayoutChange">
                            <a-select-option value="thermal104">Thermal 104mm</a-select-option>
                            <a-select-option value="a4">A4 Paper</a-select-option>
                            <a-select-option value="a5">A5 Paper</a-select-option>
                        </a-select>
                    </a-space>
                </div>
                <div class="os-btn-row">
                    <a-button v-if="customer.email && isVerified" type="primary" @click="sendInvoiceMail(order.xid, selectedLang)" :loading="isSending">
                        <template #icon><SendOutlined /></template>
                        {{ $t("common.send_invoice") }}
                    </a-button>
                    <a-button type="default" @click="downloadInvoice">
                        <template #icon><DownloadOutlined /></template>
                        Download Invoice
                    </a-button>
                    <a-button type="primary" @click="printInvoice">
                        <template #icon><PrinterOutlined /></template>
                        {{ $t("common.print_invoice") }}
                    </a-button>
                </div>
            </div>
        </template>
    </a-modal>
</template>

<script>
import { ref, defineComponent, onMounted, computed } from "vue";
import { PrinterOutlined, SendOutlined, DownloadOutlined } from "@ant-design/icons-vue";
import common from "../../../../common/composable/common";
import QRcodeGenerator from "../../../../common/components/barcode/QRcodeGenerator.vue";
import { notification } from "ant-design-vue";
import { useI18n } from "vue-i18n";

export default defineComponent({
    props: ["visible", "order", "description"],
    emits: ["closed", "success"],
    components: { PrinterOutlined, QRcodeGenerator, SendOutlined, DownloadOutlined },

    setup(props, { emit }) {
        const { t } = useI18n();
        const { formatAmountCurrency, formatDate, selectedWarehouse, selectedLang } = common();

        // Debug: Check if description prop is received
        console.log('DmartInvoice - Props:', props);
        console.log('DmartInvoice - Description:', props.description);

        const isSending = ref(false);
        const isVerified = ref("");
        const selectedPrintLayout = ref("thermal104");

        onMounted(() => {
            axiosAdmin.get("verified-email").then((res) => {
                isVerified.value = res.data?.verified;
            });
        });

        /* ── localStorage customer ──────────────────────────── */
        const localCustomer = computed(() => {
            try {
                const raw = localStorage.getItem("pos_selected_customer");
                return raw ? JSON.parse(raw) : null;
            } catch {
                return null;
            }
        });

        // Merge: prioritize selected customer from localStorage, then order.user
        const customer = computed(() => {
            const lc = localCustomer.value || {};
            const u = props.order?.user || {};
            
            // Try multiple address fields to get the right customer address
            const getAddress = () => {
                // Priority 1: Selected customer from localStorage (most important for POS)
                if (lc.address) return lc.address;
                if (lc.billing_address) return lc.billing_address;
                if (lc.shipping_address) return lc.shipping_address;
                if (lc.full_address) return lc.full_address;
                
                // Priority 2: Order user address fields
                if (u.address) return u.address;
                if (u.billing_address) return u.billing_address;
                if (u.shipping_address) return u.shipping_address;
                if (u.full_address) return u.full_address;
                
                // Priority 3: Order level address fields
                if (props.order?.billing_address) return props.order.billing_address;
                if (props.order?.shipping_address) return props.order.shipping_address;
                if (props.order?.customer_address) return props.order.customer_address;
                
                return "";
            };
            
            return {
                name:    lc.name    || u.name    || "Walk-in Customer",
                phone:   lc.phone   || u.phone   || "",
                email:   lc.email   || u.email   || "",
                address: getAddress(),
            };
        });

        /* ── helpers ───────────────────────────────────────── */
        const getTime = (dateStr) => {
            if (!dateStr) return '';
            const d = new Date(dateStr);
            return d.toTimeString().slice(0, 8);
        };

        const getTaxRate = (item) => {
            if (item.tax_rate !== null && item.tax_rate !== undefined && item.tax_rate !== '') return Number(item.tax_rate);
            const sub = Number(item.subtotal) || 0;
            const tax = Number(item.total_tax || item.tax_amount) || 0;
            const taxable = sub - tax;
            if (taxable > 0 && tax > 0) return Number(((tax / taxable) * 100).toFixed(0));
            return 0;
        };

        /* ── computed financials ────────────────────────────── */
        const grossAmount = computed(() => {
            if (!props.order?.items) return 0;
            return props.order.items.reduce((s, i) => s + (Number(i.subtotal || 0) - Number(i.total_tax || 0)), 0);
        });

        const totalTax = computed(() => {
            if (!props.order?.items) return 0;
            return props.order.items.reduce((s, i) => s + Number(i.total_tax || 0), 0);
        });

        // Extract customer state from address
        const getCustomerState = (address) => {
            if (!address) return '';
            const addr = address.toLowerCase();
            const stateKeywords = {
                'gujarat': ['gujarat', 'gujrat', 'surat', 'ahmedabad', 'vadodara', 'rajkot', 'gandhinagar', 'bharuch', 'anand', 'navsari', 'valsad', 'bhavnagar', 'jamnagar'],
                'maharashtra': ['maharashtra', 'mumbai', 'pune', 'nagpur', 'thane', 'nashik'],
                'rajasthan': ['rajasthan', 'jaipur', 'udaipur', 'jodhpur', 'ajmer'],
                'delhi': ['delhi', 'new delhi'],
                'karnataka': ['karnataka', 'bangalore', 'bengaluru', 'mysore'],
                'tamil nadu': ['tamil nadu', 'chennai', 'coimbatore', 'madurai'],
                'uttar pradesh': ['uttar pradesh', 'lucknow', 'kanpur', 'agra', 'noida'],
                'west bengal': ['west bengal', 'kolkata', 'howrah'],
                'andhra pradesh': ['andhra pradesh', 'hyderabad', 'vizag', 'vijayawada'],
                'telangana': ['telangana', 'hyderabad', 'warangal']
            };
            
            for (const [state, keywords] of Object.entries(stateKeywords)) {
                if (keywords.some(keyword => addr.includes(keyword))) {
                    return state;
                }
            }
            return '';
        };

        // Determine if transaction is intra-state (same state) or inter-state (different state)
        const isIntraState = computed(() => {
            const sellerState = selectedWarehouse.value?.state || '';
            const customerState = getCustomerState(customer.value.address);
            return sellerState && customerState && sellerState.toLowerCase() === customerState.toLowerCase();
        });

        // Calculate taxable amount (subtotal without tax)
        const taxableAmount = computed(() => {
            if (!props.order?.items) return 0;
            return props.order.items.reduce((sum, item) => {
                return sum + (Number(item.subtotal || 0) - Number(item.total_tax || 0));
            }, 0);
        });

        // Item-wise GST calculation based on customer address
        const itemGSTDetails = computed(() => {
            if (!props.order?.items) return { cgst: 0, sgst: 0, igst: 0 };
            
            let totalCGST = 0;
            let totalSGST = 0;
            let totalIGST = 0;
            
            // Get customer state from selected customer address (priority-based)
            const customerState = getCustomerState(customer.value.address);
            const sellerState = selectedWarehouse.value?.state || '';
            const isIntraStateTransaction = sellerState && customerState && sellerState.toLowerCase() === customerState.toLowerCase();
            
            props.order.items.forEach(item => {
                const itemTaxableAmount = Number(item.subtotal || 0) - Number(item.total_tax || 0);
                const itemTaxRate = getTaxRate(item);
                
                if (isIntraStateTransaction) {
                    // Intra-state: Split tax into CGST and SGST
                    const cgstAmount = itemTaxableAmount * (itemTaxRate / 2) / 100;
                    const sgstAmount = itemTaxableAmount * (itemTaxRate / 2) / 100;
                    totalCGST += cgstAmount;
                    totalSGST += sgstAmount;
                } else {
                    // Inter-state: Apply IGST
                    const igstAmount = itemTaxableAmount * itemTaxRate / 100;
                    totalIGST += igstAmount;
                }
            });
            
            return {
                cgst: totalCGST,
                sgst: totalSGST,
                igst: totalIGST
            };
        });

        // Tax amounts based on item-wise calculation
        const cgstAmount = computed(() => itemGSTDetails.value.cgst);
        const sgstAmount = computed(() => itemGSTDetails.value.sgst);
        const igstAmount = computed(() => itemGSTDetails.value.igst);

        // Calculate effective tax rates for display
        const cgstRate = computed(() => {
            if (taxableAmount.value === 0 || cgstAmount.value === 0) return 0;
            return Number(((cgstAmount.value / taxableAmount.value) * 100).toFixed(2));
        });
        
        const sgstRate = computed(() => {
            if (taxableAmount.value === 0 || sgstAmount.value === 0) return 0;
            return Number(((sgstAmount.value / taxableAmount.value) * 100).toFixed(2));
        });
        
        const igstRate = computed(() => {
            if (taxableAmount.value === 0 || igstAmount.value === 0) return 0;
            return Number(((igstAmount.value / taxableAmount.value) * 100).toFixed(2));
        });

        // Get transaction state info for debugging
        const transactionInfo = computed(() => {
            const customerState = getCustomerState(customer.value.address);
            const sellerState = selectedWarehouse.value?.state || '';
            const isIntraStateTransaction = sellerState && customerState && sellerState.toLowerCase() === customerState.toLowerCase();
            return {
                customerState,
                sellerState,
                isIntraState: isIntraStateTransaction,
                customerAddress: customer.value.address
            };
        });

        const paidAmount = computed(() =>
            props.order?.order_payments?.reduce((s, p) => s + Number(p.amount || 0), 0) || 0
        );
        const dueAmount = computed(() => (props.order?.total || 0) - paidAmount.value);

        /* ── inline print CSS ───────────────────────────────── */
        const getCSS = () => `
            *{margin:0;padding:0;box-sizing:border-box}
            body{font-family:Arial,sans-serif;font-size:10px;color:#111;background:#fff}
            .os-wrap{width:100%;max-width:390px;margin:0 auto;padding:10px 9px}
            .os-header{text-align:center;margin-bottom:6px}
            .os-logo{display:flex;justify-content:center;margin-bottom:3px}
            .os-logo-img{max-width:44px;max-height:44px;object-fit:contain}
            .os-name{font-size:16px;font-weight:800;color:#111;letter-spacing:.3px;margin-bottom:1px}
            .os-tagline{font-size:8px;letter-spacing:2.5px;color:#555;text-transform:uppercase;margin-bottom:3px}
            .os-addr{font-size:8.5px;color:#333;line-height:1.45;margin-bottom:1px}
            .os-contact{font-size:8.5px;color:#333}
            .os-hr{border:none;border-top:1px solid #888;margin:6px 0}
            .os-hr-thin{border:none;border-top:.5px solid #ccc;margin:5px 0}
            .os-meta{display:flex;justify-content:space-between;font-size:9.5px}
            .os-meta-left,.os-meta-right{flex:1}
            .os-mrow{display:flex;gap:2px;margin-bottom:1.5px}
            .os-mr-row{justify-content:flex-end}
            .os-ml{color:#555;min-width:62px}
            .os-mv{font-weight:600;color:#111}
            .os-sec-title{font-size:9.5px;font-weight:700;text-transform:uppercase;margin:0 0 2px}
            .os-customer{font-size:9.5px;margin-bottom:5px}
            .os-crow{display:flex;margin-bottom:1px}
            .os-cl{min-width:44px;color:#555}
            .os-cv{color:#111}
            .os-table{width:100%;border-collapse:collapse;font-size:8.5px;margin:5px 0 3px}
            .os-thead-tr{background:#1a1a1a;color:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}
            .os-th{padding:4px 2px;font-weight:700;font-size:7.5px;border:none}
            .os-td{padding:3px 2px;border-bottom:.3px solid #ddd;vertical-align:middle}
            .os-tl{text-align:left}.os-tc{text-align:center}.os-tr{text-align:right}
            .os-totals{font-size:9.5px}
            .os-trow{display:flex;justify-content:space-between;margin-bottom:2px;color:#333}
            .os-net{display:flex;justify-content:space-between;font-size:13px;font-weight:800;color:#111;padding:2px 0}
            .os-bank{font-size:9.5px;margin-bottom:4px}
            .os-brow{display:flex;margin-bottom:1px}
            .os-bl{min-width:44px;color:#555}
            .os-bv{color:#111}
            .os-terms{font-size:9px;color:#444;font-style:italic;line-height:1.45;margin-bottom:2px}
            .os-sig{text-align:center;font-size:9.5px;margin:8px 0 5px}
            .os-for{margin-bottom:16px}
            .os-sig-gap{height:24px;border-bottom:.5px dashed #999;width:88px;margin:0 auto 3px}
            .os-auth{font-weight:700;margin-bottom:1px}
            .os-store-sig{color:#555}
            .os-qr{display:flex;justify-content:center;margin:5px 0}
            .os-footer{text-align:center;font-size:9px;font-weight:600;color:#333;padding-top:5px;border-top:.5px solid #bbb;margin-top:4px;margin-bottom:15px}
            .os-footer-content{display:flex;justify-content:space-between;align-items:flex-start;text-align:left}
            .os-footer-left{flex:1;text-align:left}
            .os-footer-right{flex:1;text-align:right}
            .os-company-info{margin-top:8px;font-size:8px;font-weight:normal;line-height:1.4}
            .os-footer-left p:first-child{font-style:italic;color:#666;margin-bottom:5px}
            .os-footer-right p{margin:2px 0;font-size:8px}
            @media print{
                @page{size:104mm auto;margin:3mm}
                body{margin:0;padding:0;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}
                .os-thead-tr{background:#1a1a1a!important;color:#fff!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}
            }
        `;

        /* ── print ──────────────────────────────────────────── */
        const printInvoice = () => {
            const content = document.getElementById("dmart-invoice").innerHTML;
            let w = selectedPrintLayout.value === 'a4' ? 800 : selectedPrintLayout.value === 'a5' ? 600 : Math.round(104 * 3.78);
            const win = window.open("", "", `height=700,width=${w}`);
            win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><style>${getCSS()}</style></head><body>${content}</body></html>`);
            win.document.close();
            setTimeout(() => win.print(), 400);
        };

        /* ── download ───────────────────────────────────────── */
        const downloadInvoice = () => {
            const content = document.getElementById("dmart-invoice").innerHTML;
            const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Invoice-${props.order?.invoice_number}</title><style>${getCSS()}</style></head><body>${content}</body></html>`;
            const blob = new Blob([html], { type: 'text/html' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `Invoice_${props.order?.invoice_number}.html`;
            document.body.appendChild(a); a.click();
            document.body.removeChild(a); URL.revokeObjectURL(url);
            notification.success({ message: t("common.success"), description: "Invoice downloaded successfully", duration: 3 });
        };

        /* ── mail ───────────────────────────────────────────── */
        const sendInvoiceMail = async (xid, lang) => {
            isSending.value = true;
            try {
                await axiosAdmin.get(`send-mail/${xid}/${lang}`);
                notification.success({ message: t("common.success"), description: t("common.mail_sent_successfully"), duration: 4.5 });
            } catch {
                notification.error({ message: t("common.error"), description: t("common.failed_to_send_mail"), duration: 4.5 });
            } finally { isSending.value = false; }
        };

        const onClose = () => emit("closed");
        const onPrintLayoutChange = (v) => { selectedPrintLayout.value = v; };

        return {
            onClose, formatDate, getTime, getTaxRate,
            selectedWarehouse, formatAmountCurrency,
            taxableAmount, isIntraState, cgstRate, sgstRate, igstRate,
            cgstAmount, sgstAmount, igstAmount,
            paidAmount, dueAmount,
            printInvoice, downloadInvoice, sendInvoiceMail,
            selectedPrintLayout, onPrintLayoutChange,
            selectedLang, isSending, isVerified,
            customer,
            description: props.description || '',
            itemGSTDetails, transactionInfo,
        };
    },
});
</script>

<style scoped>
/* ── modal invoice preview ── */
#dmart-invoice { background: #fff; }

.os-wrap {
    width: 100%;
    max-width: 390px;
    margin: 0 auto;
    padding: 10px 9px;
    font-family: Arial, sans-serif;
    font-size: 10px;
    color: #111;
    background: #fff;
}

/* HEADER */
.os-header { text-align: center; margin-bottom: 6px; }
.os-logo { display: flex; justify-content: center; margin-bottom: 3px; }
.os-logo-img { max-width: 44px; max-height: 44px; object-fit: contain; }
.os-name { font-size: 16px; font-weight: 800; color: #111; letter-spacing: .3px; margin-bottom: 1px; }
.os-tagline { font-size: 8px; letter-spacing: 2.5px; color: #555; text-transform: uppercase; margin-bottom: 3px; }
.os-addr { font-size: 8.5px; color: #333; line-height: 1.45; margin-bottom: 1px; }
.os-contact { font-size: 8.5px; color: #333; }

/* RULES */
.os-hr { border: none; border-top: 1px solid #888; margin: 6px 0; }
.os-hr-thin { border: none; border-top: .5px solid #ccc; margin: 5px 0; }

/* META */
.os-meta { display: flex; justify-content: space-between; font-size: 9.5px; }
.os-meta-left, .os-meta-right { flex: 1; }
.os-mrow { display: flex; gap: 2px; margin-bottom: 1.5px; }
.os-mr-row { justify-content: flex-end; }
.os-ml { color: #555; min-width: 62px; }
.os-mv { font-weight: 600; color: #111; }

/* SECTION TITLE */
.os-sec-title { font-size: 9.5px; font-weight: 700; text-transform: uppercase; margin: 0 0 2px; color: #111; }

/* CUSTOMER */
.os-customer { font-size: 9.5px; margin-bottom: 5px; }
.os-crow { display: flex; margin-bottom: 1px; }
.os-cl { min-width: 44px; color: #555; }
.os-cv { color: #111; }

/* ITEMS TABLE */
.os-table { width: 100%; border-collapse: collapse; font-size: 8.5px; margin: 5px 0 3px; }
.os-thead-tr {
    background: #1a1a1a;
    color: #fff;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
}
.os-th { padding: 4px 2px; font-weight: 700; font-size: 7.5px; border: none; }
.os-td { padding: 3px 2px; border-bottom: .3px solid #ddd; vertical-align: middle; }
.os-tl { text-align: left; }
.os-tc { text-align: center; }
.os-tr { text-align: right; }

/* TOTALS */
.os-totals { font-size: 9.5px; }
.os-trow { display: flex; justify-content: space-between; margin-bottom: 2px; color: #333; }
.os-trow.gst-cgst { color: #2c5aa0; font-weight: 600; }
.os-trow.gst-sgst { color: #2c5aa0; font-weight: 600; }
.os-trow.gst-igst { color: #d35400; font-weight: 600; }
.os-trow.total-tax { color: #111; font-weight: 700; border-top: 1px solid #ddd; padding-top: 2px; margin-top: 2px; }

/* NET AMOUNT */
.os-net {
    display: flex;
    justify-content: space-between;
    font-size: 13px;
    font-weight: 800;
    color: #111;
    padding: 2px 0;
}

/* BANK */
.os-bank { font-size: 9.5px; margin-bottom: 4px; }
.os-brow { display: flex; margin-bottom: 1px; }
.os-bl { min-width: 44px; color: #555; }
.os-bv { color: #111; }

/* DESCRIPTION */
.os-description { margin-bottom: 4px; }
.os-desc-text { font-size: 9px; color: #444; line-height: 1.4; margin-bottom: 2px; }

/* TERMS */
.os-terms { font-size: 9px; color: #444; font-style: italic; line-height: 1.45; margin-bottom: 2px; }

/* SIGNATURE */
.os-sig { text-align: center; font-size: 9.5px; margin: 8px 0 5px; }
.os-for { margin-bottom: 16px; }
.os-sig-gap {
    height: 24px;
    border-bottom: .5px dashed #999;
    width: 88px;
    margin: 0 auto 3px;
}
.os-auth { font-weight: 700; margin-bottom: 1px; }
.os-store-sig { color: #555; }

/* QR */
.os-qr { display: flex; justify-content: center; margin: 5px 0; }

/* FOOTER */
.os-footer {
    text-align: center;
    font-size: 9px;
    font-weight: 600;
    color: #333;
    padding-top: 5px;
    border-top: .5px solid #bbb;
    margin-top: 4px;
    margin-bottom: 15px;
}

.os-thank-you {
    font-style: italic;
    color: #666;
    margin-top: 12px;
    margin-bottom: 5px;
    font-size: 9px;
    text-align: center;
}

.os-footer-content {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    text-align: left;
}

.os-footer-left {
    flex: 1;
    text-align: left;
}

.os-footer-right {
    flex: 1;
    text-align: right;
}

.os-company-info {
    margin-top: 8px;
    font-size: 8px;
    font-weight: normal;
    line-height: 1.4;
}

.os-footer-left p:first-child {
    margin-bottom: 5px;
}

.os-footer-right p {
    margin: 2px 0;
    font-size: 8px;
}

/* MODAL FOOTER */
.os-modal-footer { display: flex; flex-direction: column; gap: 8px; }
.os-layout-pick { display: flex; align-items: center; }
.os-btn-row { display: flex; gap: 8px; justify-content: flex-end; flex-wrap: wrap; }
</style>