<template>
  <a-modal
    :open="visible"
    :centered="true"
    :maskClosable="false"
    :title="$t('common.print_invoice')"
    width="900px"
    @cancel="onClose"
  >
    <div id="pos-invoice">
      <div
        id="pos-invoice-inner"
        :class="['invoice-root', sizeClass]"
        v-if="order && order.xid"
        style="margin: 0 auto"
      >
        <!-- TOP HEADER (STORE INFO) -->
        <div class="invoice-header">
         <div class="invoice-meta-center">
            <h2 class="tax-invoice-title">
              {{ $t('sales.tax_invoice') }}
            </h2>
          </div>
          <img
            class="invoice-logo"
            :src="selectedWarehouse.logo_url"
            :alt="selectedWarehouse.name"
          />
         <div class="invoice-header-text">
  <h1 class="store-name">
    {{ selectedWarehouse.name }}
  </h1>
  <p class="store-address">
    {{ selectedWarehouse.address }}
  </p>

  <!-- PHONE + EMAIL on one line -->
  <p class="store-contact-line">
    <span v-if="selectedWarehouse.phone">
      {{ $t('common.phone') }}: {{ selectedWarehouse.phone }}
    </span>
    <span v-if="selectedWarehouse.email">
      &nbsp;&nbsp;|&nbsp;&nbsp;{{ $t('common.email') }}: {{ selectedWarehouse.email }}
    </span>
  </p>

  <!-- GSTIN: New line, bold, slightly indented, centered -->
  <p class="store-gstin-line">
    <strong>GSTIN:</strong> {{ displayGSTIN }}
  </p>
</div>
        </div>

        

        <!-- BILL TO (LIKE "BILL TO PARTY" BLOCK) -->
       <!-- BILL TO + INVOICE DETAILS (NOW 100% VISIBLE IN PDF) -->
<div class="bill-party-row">
  <!-- LEFT: Customer Details -->
  <div class="bill-party-left">
    <h4 class="bill-title">Bill To Party</h4>
    <p class="party-line party-name">
      {{ order.user?.name || posSelectedCustomer?.name || 'Walk-in Customer' }}
    </p>
    <p v-if="order.user?.phone || posSelectedCustomer?.phone" class="party-line">
      Mo: {{ order.user?.phone || posSelectedCustomer?.phone }}
    </p>
<br/>
    <!-- GSTIN: Clean, No <br/>, No Extra Bold -->
    <p v-if="order.user?.gst_number" class="party-line">
      <strong>GSTIN:</strong> {{ order.user.gst_number }}
    </p>

    <p v-if="finalCustomerAddress" class="party-line address-line">
      {{ finalCustomerAddress }}
    </p>
    <p v-else class="party-line text-muted"><em>Address not available</em></p>
  </div>

  <!-- RIGHT: Invoice Details (NOW 100% VISIBLE IN PDF) -->
 <div class="bill-party-right">
  <table class="invoice-details-table-print-safe">
    <tbody>
      <tr>
        <td class="meta-label">Invoice No</td>
        <td class="meta-value">: {{ order.invoice_number }}</td>
      </tr>
      <tr>
        <td class="meta-label">Date</td>
        <td class="meta-value">: {{ formatDate(order.order_date) }}</td>
      </tr>
      <tr>
        <td class="meta-label">Generated by</td>
        <td class="meta-value">: {{ displayName || 'Admin' }}</td>
      </tr>
      <tr>
        <td class="meta-label">Generated at</td>
        <td class="meta-value">: {{ currentTime }}</td>
      </tr>
      <tr v-if="selectedWarehouse.city || selectedWarehouse.state">
        <td class="meta-label">Location</td>
        <td class="meta-value">: {{ [selectedWarehouse.city, selectedWarehouse.state].filter(Boolean).join(', ') }}</td>
      </tr>
    </tbody>
  </table>
</div>
</div>


        <!-- ITEMS TABLE -->
        <div class="tax-invoice-items">
          <table class="items-table">
            <thead>
              <tr>
                <th style="width: 5%">NO</th>
                <th style="width: 25%">{{ $t('common.item') }}</th>
                <th style="width: 10%">{{ 'HSN NO' }}</th>
                <th style="width: 8%">{{ $t('product.unit') }}</th>
                <th style="width: 8%">{{ $t('common.qty') }}</th>
                <th style="width: 12%">{{ $t('common.rate') }}</th>
               
                <th style="width: 8%">{{ $t('product.tax') }} %</th>
                <th style="width: 10%; text-align: right">
                  {{ $t('common.total') }}
                </th>
              </tr>
            </thead>
            <tbody>
              <tr
                class="item-row"
                v-for="(item, index) in order.items"
                :key="item.xid"
              >
                <td class="center">
                  {{ index + 1 }}
                </td>

                <!-- Item name + custom fields (if backend later returns them) -->
                <td>
                  <div class="item-name">
                    {{ item.product?.name }}
                  </div>
                 
                </td>

                <!-- HSN NO -->
              <td class="center">
  {{ item.hsn_code || item.product?.hsn_code || "-" }}
</td>
<div
  v-if="item.custom_fields && item.custom_fields.length"
  class="item-custom-fields"
>
  <span
    v-for="cf in item.custom_fields"
    :key="cf.id || cf.name || cf.label"
    class="item-custom-field-line"
  >
    {{ cf.label || cf.name }}: {{ cf.value }}
  </span>
</div>

                <!-- UNIT -->
                <td class="center">
                  {{ item.unit?.short_name || item.unit?.name || '-' }}
                </td>

                <!-- QTY -->
                <td class="center">
                  {{ item.quantity }}
                </td>

                <!-- RATE -->
                <td class="right">
                  {{ formatAmountCurrency(item.unit_price) }}
                </td>

             

                <!-- GST % -->
                <td class="center">
                  <span v-if="getTaxRate(item)">
                    {{ getTaxRate(item) }}
                  </span>
                  <span v-else>-</span>
                </td>

                <!-- TOTAL (WITH TAX) -->
                <td class="right">
                  {{ formatAmountCurrency(item.subtotal) }}
                </td>
              </tr>

            </tbody>
          </table>
        </div>

        <!-- TOTALS (GROSS / SGST / CGST / IGST / NET) -->
        <!-- FINAL SINGLE BOX: TOTALS + GST SUMMARY + PAID/DUE -->
<!-- FINAL TOTALS BOX - NOW LOOKS LIKE ITEMS TABLE (BEAUTIFUL & PROFESSIONAL) -->
<div class="final-totals-box">
  <table class="items-table" style="margin-top: 20px; border: 2px solid #000;">
    <tbody>
      <!-- ROW 1: GROSS + SGST + CGST + IGST + NET -->
      <tr class="summary-row">
        <td class="label-strong">GROSS AMT :</td>
        <td class="value-right">{{ formatAmountCurrency(getGrossAmount(order)) }}</td>
        <td class="label-strong">SGST :</td>
        <td class="value-right">{{ formatAmountCurrency(computedSGST) }}</td>
        <td class="label-strong">CGST :</td>
        <td class="value-right">{{ formatAmountCurrency(computedCGST) }}</td>
      </tr>
      <tr class="summary-row">
        <td class="label-strong">IGST :</td>
        <td class="value-right">{{ formatAmountCurrency(computedIGST) }}</td>
        <td class="label-strong">NET AMOUNT :</td>
        <td class="value-right big-total" colspan="3">{{ formatAmountCurrency(order.total) }}</td>
      </tr>

      <!-- GST SLAB SUMMARY TABLE (Inside as a clean mini table) -->
    <!-- PAID + MODE + DUE – ALL IN ONE CLEAN LINE (EXACTLY LIKE YOUR EXAMPLE) -->
<tr class="final-paid-due-row">
  <td colspan="8" style="padding: 12px 10px; background: #fff8e1; border-top: 3px double #000;">
    <div class="paid-due-with-mode">
      <span class="paid-part">
        <strong>PAID AMOUNT :</strong> 
        {{ formatAmountCurrency(order.paid_amount) }}
        <span v-if="order.paid_amount > 0 && order.order_payments && order.order_payments.length" class="payment-modes">
          ({{
            order.order_payments
              .map(p => p.payment?.payment_mode?.name || 'Cash')
              .filter(Boolean)
              .join(' + ')
          }})
        </span>
      </span>

      <span class="due-part">
        <strong>DUE AMOUNT :</strong> 
        <span class="due-amount">{{ formatAmountCurrency(order.due_amount) }}</span>
      </span>
    </div>
  </td>
</tr>

      <!-- PAID & DUE AMOUNT -->
      <tr style="background: #fff8e1; font-size: 14.5px;">
        <td class="label-strong">PAID AMOUNT :</td>
        <td class="value-right paid-strong">{{ formatAmountCurrency(order.paid_amount) }}</td>
        <td class="label-strong">DUE AMOUNT :</td>
        <td class="value-right due-strong" colspan="3">{{ formatAmountCurrency(order.due_amount) }}</td>
      </tr>

      <!-- RUPEES IN WORDS -->
      <tr v-if="order.amount_in_words">
        <td colspan="6" style="padding: 10px 12px; font-style: italic; color: #555; background: #f5f5f5; font-size: 13px;">
          <strong>Rupees in Words:</strong> {{ order.amount_in_words }}
        </td>
      </tr>
    </tbody>
  </table>
</div>

        <!-- PAYMENT MODE -->
        

        <!-- DISCOUNT / TAX SUMMARY (OPTIONAL) -->
        

        <!-- BANK DETAIL + TERMS + SIGN – BOX TABLE LIKE PDF -->
        <!-- BOTTOM SECTION – EXACTLY LIKE YOUR IMAGE -->
<!-- BOTTOM SECTION – PERFECT SINGLE BOX BANK DETAILS + TERMS & SIGNATURE -->
<div class="bottom-section">
  <!-- 1. BANK DETAILS – ONE CLEAN HORIZONTAL BOX (LIKE YOUR IMAGE) -->
  <div class="bank-details-box">
  <strong class="bank-title">BANK DETAIL :</strong>
  <div class="bank-items">
    <span>A/c No : {{ bankDetailsToShow.accountNo }}</span>
    <span class="separator">|</span>
    <span>Bank : {{ bankDetailsToShow.bank }}</span>
    <span class="separator">|</span>
    <span>Branch : {{ bankDetailsToShow.branch }}</span>
    <span class="separator">|</span>
    <span>IFSC : {{ bankDetailsToShow.ifsc }}</span>
  </div>
</div>

  <!-- 2. TWO BOXES BELOW – TERMS + SIGNATURE -->
  <div class="bottom-boxes-row">
    <!-- LEFT: TERMS OF SALES -->
    <div class="terms-box-final">
      <div class="terms-header">Terms Of Sales :</div>
      <div class="terms-content">
        {{ selectedWarehouse.invoice_terms || 'Goods once sold will be taken back or exchanged within 10 Days.' }}
      </div>
      <div class="for-company">
        For : {{ selectedWarehouse.name || 'SHAYONA HANDLOOM & HANDICRAFT' }}
      </div>
    </div>

    <!-- RIGHT: AUTHORISED SIGNATORY -->
    <div class="signature-box-final">
      <div class="signature-title">Authorised Signatory</div>
      <div class="signature-space"></div>
      <div class="company-name-bottom">
        {{ selectedWarehouse.name || 'SHAYONA HANDLOOM & HANDICRAFT' }}
      </div>
    </div>
  </div>
</div>
        <!-- BARCODE / QR + THANKS -->
        <div
          v-if="selectedWarehouse.barcode_type == 'barcode'"
          class="barcode-details"
        >
          <BarcodeGenerator
            :value="order.invoice_number + ''"
            :height="25"
            :width="1"
            :fontSize="15"
            :elementTag="'svg'"
          />
        </div>
        <div v-else style="text-align: center" class="qrcode-details">
          <QRcodeGenerator :text="order.invoice_number + ''" />
        </div>

        <div class="thanks-details">
          <h3>{{ $t('invoice.thanks_message') }}</h3>
          <tr>
 
</tr>

        </div>
      </div>
    </div>

    <template #footer>
  <div class="footer-button">
    <a-button v-if="order?.user?.email && isVerified" type="primary" @click="sendInvoiceMail(order.xid, selectedLang)" :loading="isSending">
      <template #icon><SendOutlined /></template>
      {{ $t('common.send_invoice') }}
    </a-button>

    <!-- New: Download PDF Button -->
    <a-button type="default" @click="downloadPdf" style="margin-right: 8px;">
      <template #icon><DownloadOutlined /></template>
      Download PDF
    </a-button>

    <!-- Old Print Button (still works) -->
    <a-button type="primary" @click="printInvoice">
      <template #icon><PrinterOutlined /></template>
      {{ $t('common.print_invoice') }}
    </a-button>
  </div>
</template>
  </a-modal>
</template>

<script>
import { ref, defineComponent, onMounted, computed, watch, nextTick } from "vue";
import { PrinterOutlined, SendOutlined } from "@ant-design/icons-vue";
import common from "../../../../common/composable/common";
import BarcodeGenerator from "../../../../common/components/barcode/BarcodeGenerator.vue";
import QRcodeGenerator from "../../../../common/components/barcode/QRcodeGenerator.vue";
import { notification } from "ant-design-vue";
import { useI18n } from "vue-i18n";
import html2pdf from 'html2pdf.js';
import { DownloadOutlined } from '@ant-design/icons-vue';

const posInvoiceCssUrl = window.config.pos_invoice_css;

// Static fallbacks (used when warehouse doesn't have data)
const FALLBACK_GSTIN = "24BNGPG0699R1ZD";
const FALLBACK_BANK = {
 
  accountNo: "18650200016691",
  bank: "THE FEDERAL BANK",
  branch: "SURAT VARACHHA",
  ifsc: "FDRL0001865",
};
const authUser = JSON.parse(localStorage.getItem('auth_user')) || {};

// Extract the role and display_name from authUser
const displayName = authUser.name || {};
const currentTime = new Date().toLocaleString();

// Log the display_name in the console
console.log("User Display Name:", displayName);

export default defineComponent({
  props: {
    visible: { type: Boolean, default: false },
    order: { type: Object, default: null },
    size: { type: String, default: "A4" }, // 'A4' | 'A5' | '80mm' | '58mm'
    autoOpen: { type: Boolean, default: false },
  },
  emits: ["closed", "success"],
 components: {
  PrinterOutlined,
  SendOutlined,
  DownloadOutlined,
  BarcodeGenerator,
  QRcodeGenerator,
},
  setup(props, { emit }) {
    const { t } = useI18n();
    const {
      formatAmountCurrency,
      formatDate,
      selectedWarehouse,
      selectedLang,
    } = common();

    const isSending = ref(false);
    const isVerified = ref("");

    onMounted(() => {
      axiosAdmin.get("verified-email").then((response) => {
        isVerified.value = response.data?.verified;
      });
    });

    // Debug: log full order/items whenever order changes
    watch(
      () => props.order,
      (o) => {
        if (o) {
          console.log("POS Invoice Order:", JSON.parse(JSON.stringify(o)));
          if (Array.isArray(o.items)) {
            console.log(
              "POS Invoice Order Items:",
              JSON.parse(JSON.stringify(o.items))
            );
          }
        }
      },
      { immediate: true }
    );
const downloadPdf = () => {
  printInvoice(); // Reuse same function
};
    const onClose = () => emit("closed");
const posSelectedCustomer = computed(() => {
      try {
        const raw = localStorage.getItem('pos_selected_customer');
        return raw ? JSON.parse(raw) : null;
      } catch (e) {
        return null;
      }
    });

    // Final customer address to use for GST logic
    const finalCustomerAddress = computed(() => {
      return (props.order?.user?.address || posSelectedCustomer.value?.address || "").trim();
    });

    // Smart Gujarat Detection – Works with "Surat,Gujarat", "Surat Gujarat", "GJ", etc.
    const customerState = computed(() => {
      const addr = finalCustomerAddress.value.toLowerCase();
      const gujaratKeywords = [
        "gujarat", "gujrat", "gj", "surat", "ahmedabad", "vadodara", "rajkot",
        "bhavnagar", "jamnagar", "anand", "gandhinagar", "bharuch", "valsad", "navsari"
      ];
      return gujaratKeywords.some(kw => addr.includes(kw)) ? "Gujarat" : "Other State";
    });

    const isIntraState = computed(() => customerState.value === "Gujarat");

// BEST & MOST ACCURATE METHOD (Recommended)
const totalTaxAmount = computed(() => {
  if (!props.order?.items || !Array.isArray(props.order.items)) return 0;
  
  return props.order.items.reduce((sum, item) => {
    return sum + Number(item.total_tax || 0);
  }, 0);
});
console.log("Total Tax Amount:", totalTaxAmount);
    const computedSGST = computed(() => isIntraState.value ? totalTaxAmount.value / 2 : 0);
    const computedCGST = computed(() => isIntraState.value ? totalTaxAmount.value / 2 : 0);
    const computedIGST = computed(() => isIntraState.value ? 0 : totalTaxAmount.value);
    console.log("SGST:", computedSGST.value);
    console.log("CGST:", computedCGST.value);
    console.log("IGST:", computedIGST.value);
    
    watch(
      () => props.order,
      (newOrder) => {
    if (!newOrder || !newOrder.xid) return;

    const tax = Number(newOrder.tax_amount) || 0;
    const detectedState = customerState.value;
    const isGujarat = detectedState === "Gujarat";

    console.log("════════════════════════════════");
    console.log("GST SPLIT DEBUG (Invoice: %s)", newOrder.invoice_number);
    console.log("Customer Address →", newOrder.user?.address || "N/A");
    console.log("Customer City    →", newOrder.user?.city || "N/A");
    console.log("Detected State   →", detectedState);
    console.log("Is Gujarat?      →", isGujarat ? "YES → SGST + CGST" : "NO → IGST");
    console.log("Total Tax Amount →", tax.toFixed(2));
    console.log("→ SGST           →", computedSGST.value.toFixed(2));
    console.log("→ CGST           →", computedCGST.value.toFixed(2));
    console.log("→ IGST           →", computedIGST.value.toFixed(2));
    console.log("Check Sum        →", (computedSGST.value + computedCGST.value + computedIGST.value).toFixed(2), 
                "==", tax.toFixed(2), 
                (computedSGST.value + computedCGST.value + computedIGST.value) === tax ? "PERFECT" : "ERROR");
    console.log("════════════════════════════════\n");
  },
  { immediate: true }
);

    const sendInvoiceMail = async (xid, lang) => {
      isSending.value = true;
      try {
        await axiosAdmin.get(`send-mail/${xid}/${lang}`);
        notification.success({
          message: t("common.success"),
          description: t("common.mail_sent_successfully"),
          duration: 4.5,
        });
      } catch (error) {
        notification.error({
          message: t("common.error"),
          description: t("common.failed_to_send_mail"),
          duration: 4.5,
        });
      } finally {
        isSending.value = false;
      }
    };

    const sizeClass = computed(() => {
      const s = (props.size || "A4").toUpperCase();
      if (s === "A5") return "a5-invoice";
      if (s === "80MM") return "thermal-80";
      if (s === "58MM") return "thermal-58";
      return "a4-invoice";
    });

    const buildPrintCss = () => {
      const s = (props.size || "A4").toUpperCase();
      if (s === "A5") {
        return `
          @page { size: A5; margin: 10mm; }
          .invoice-root { max-width: 148mm; width: 148mm; }
          body, table { font-size: 12px; }
        `;
      }
      if (s === "80MM") {
        return `
          @page { size: 80mm auto; margin: 5mm; }
          .invoice-root { max-width: 80mm; width: 80mm; }
          body, table { font-size: 11px; }
          .invoice-logo { width: 70px; }
        `;
      }
      if (s === "58MM") {
        return `
          @page { size: 58mm auto; margin: 4mm; }
          .invoice-root { max-width: 58mm; width: 58mm; }
          body, table { font-size: 10px; }
          .invoice-logo { width: 60px; }
        `;
      }
      return `
        @page { size: A4; margin: 12mm; }
        .invoice-root { max-width: 210mm; width: 210mm; }
        body, table { font-size: 13px; }
      `;
    };
const getAllComponentStyles = () => {
  const styles = [];
  // Get all <style> tags in current document that belong to this component
  document.querySelectorAll('style').forEach(styleTag => {
    if (styleTag.textContent.includes('.invoice-root') || 
        styleTag.textContent.includes('.final-totals-box') ||
        styleTag.textContent.includes('.bank-details-box')) {
      styles.push(styleTag.textContent);
    }
  });
  return styles.join('\n');
};
const printInvoice = async () => {
  await nextTick(); // ← Now works!

  const element = document.getElementById('pos-invoice-inner');
  if (!element) return;

  // Force barcode/QR to render perfectly
  const svgs = element.querySelectorAll('svg');
  svgs.forEach(svg => {
    svg.setAttribute('width', '100%');
    svg.setAttribute('height', '60');
  });

  let format = 'a4';
  let margin = [8, 8, 8, 8];

  if (props.size === 'A5') format = 'a5';
  else if (props.size === '80MM') { format = [80, 'auto']; margin = [3, 3, 3, 3]; }
  else if (props.size === '58MM') { format = [58, 'auto']; margin = [2, 2, 2, 2]; }

  const opt = {
    margin,
    filename: `Invoice_${props.order?.invoice_number || 'POS'}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: {
      scale: 2,
      useCORS: true,
      letterRendering: true,
      backgroundColor: '#ffffff',
    },
    jsPDF: { unit: 'mm', format, orientation: 'portrait' },
  };

  html2pdf().set(opt).from(element).save();

  notification.success({
    message: 'Success',
    description: 'Invoice PDF downloaded!',
  });
};
    // Helpers for item-level taxable and tax rate
    const getTaxableAmount = (item) => {
      const subtotal = Number(item.subtotal) || 0;
      const tax =
        Number(item.tax_amount) ||
        Number(item.total_tax) ||
        0;
      const taxable = subtotal - tax;
      return taxable > 0 ? taxable : subtotal;
    };

    const getTaxRate = (item) => {
      if (
        item.tax_rate !== null &&
        item.tax_rate !== undefined &&
        item.tax_rate !== ""
      ) {
        return Number(item.tax_rate);
      }
      const subtotal = Number(item.subtotal) || 0;
      const tax =
        Number(item.tax_amount) ||
        Number(item.total_tax) ||
        0;
      const taxable = subtotal - tax;
      if (taxable > 0 && tax > 0) {
        return Number(((tax / taxable) * 100).toFixed(2));
      }
      return 0;
    };

    const getGrossAmount = (order) => {
      if (order.subtotal) return order.subtotal;
      const total = Number(order.total) || 0;
      const tax = Number(order.tax_amount) || 0;
      const discount = Number(order.discount) || 0;
      const shipping = Number(order.shipping) || 0;
      return total - tax + discount - shipping;
    };

    // GST slab summary from items (group by tax_rate)
    const gstSummary = computed(() => {
      const map = {};
      if (!props.order || !Array.isArray(props.order.items)) return [];

      props.order.items.forEach((item) => {
        const rate = getTaxRate(item) || 0;
        const taxable = getTaxableAmount(item) || 0;
        const tax =
          Number(item.tax_amount) ||
          Number(item.total_tax) ||
          taxable * (rate / 100);

        if (!map[rate]) {
          map[rate] = { rate, taxable: 0, taxAmount: 0, net: 0 };
        }
        map[rate].taxable += taxable;
        map[rate].taxAmount += tax;
        map[rate].net += taxable + tax;
      });

      return Object.values(map).sort((a, b) => a.rate - b.rate);
    });

    const gstSummaryTotals = computed(() => {
      return gstSummary.value.reduce(
        (acc, row) => {
          acc.taxable += row.taxable;
          acc.taxAmount += row.taxAmount;
          acc.net += row.net;
          return acc;
        },
        { taxable: 0, taxAmount: 0, net: 0 }
      );
    });

    // GSTIN + Bank details with static fallback
    const displayGSTIN = computed(() => {
      return selectedWarehouse.gst_number || FALLBACK_GSTIN;
    });

    const bankDetailsToShow = computed(() => {
      return {
        
        accountNo:
          selectedWarehouse.bank_account_no ||
          FALLBACK_BANK.accountNo,
        bank:
          selectedWarehouse.bank_name ||
          FALLBACK_BANK.bank,
        branch:
          selectedWarehouse.bank_branch ||
          FALLBACK_BANK.branch,
        ifsc:
          selectedWarehouse.ifsc_code ||
          FALLBACK_BANK.ifsc,
      };
    });

    watch(
      () => props.visible,
      (v) => {
        if (v && props.autoOpen) {
          setTimeout(() => printInvoice(), 250);
        }
      }
    );

    return {
      onClose,
      formatDate,
      displayName,
      currentTime,
      selectedWarehouse,
      formatAmountCurrency,
      printInvoice,
      selectedLang,
      sendInvoiceMail,
      isSending,
      isVerified,
      sizeClass,
      getTaxableAmount,
      getTaxRate,
      getGrossAmount,
      gstSummary,
      gstSummaryTotals,
      displayGSTIN,
      bankDetailsToShow,
      customerState,
  computedSGST,
  computedCGST,
  computedIGST,
  posSelectedCustomer,
  finalCustomerAddress,
    };
  },
});
</script>

<style>
.invoice-header {
  text-align: center;
  border-bottom: 1px dotted #ddd !important;
  padding-bottom: 6px;
}
.invoice-logo {
  width: 100px;
  margin-bottom: 4px;
}
.invoice-header-text {
  text-align: center;
  margin-top: -80px;
}

.store-contact-line {
  margin: 6px 0;
  font-size: 13px;
  font-weight: 500;
  color: #333;
}

.store-gstin-line {
  margin: 4px 0 0 0;
  font-size: 14.5px;
  font-weight: 700;
  color: #000;
  letter-spacing: 0.8px;
  text-align: center;
  padding-left: 20px;        /* This creates the beautiful indent */
  text-indent: -20px;        /* Pulls "GSTIN:" back a bit */
}

.store-gstin-line strong {
  font-weight: 900;
  color: #000;
}
.store-name {
  margin: 0;
  font-size: 18px;
  font-weight: 700;
  text-transform: uppercase;
}
.store-address {
  margin: 0;
  white-space: break-spaces;
}
.store-contact {
  margin: 0;
  font-size: 12px;
}
.store-gst {
  font-weight: 500;
}

.invoice-meta-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-top: 6px;
  border-bottom: 1px dotted #ddd !important;
  padding-bottom: 4px;
}
.tax-invoice-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
}
.invoice-meta-table {
  width: auto;
  font-size: 12px;
}
.invoice-meta-table td {
  padding: 1px 4px;
}
.meta-label {
  font-weight: 500;
  white-space: nowrap;
}
.meta-value {
  white-space: nowrap;
}

/* Bill to party row */
.bill-party-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin: 15px 0 10px;
  padding-bottom: 10px;
  border-bottom: 2px dotted #000;
  page-break-inside: avoid;
}

.bill-party-left {
  flex: 1;
  min-width: 55%;
}
.address-line {
  font-weight: 500;
  margin-top: 4px;
  white-space: pre-line;
}

.generated-info {
  background: #f8f9fa;
  padding: 10px 25px;
  border-radius: 6px;
  border: 1px solid #e0e0e0;
  display: inline-block;
  font-size: 11.5px;
  line-height: 1.4;
}

.bill-party-right {
  flex: 1;
  text-align: right;
  padding: 0 10px;
}

.invoice-details-table-print-safe {
  display: table !important;
  border-collapse: collapse;
  font-size: 13px;
  background: #f0f8ff !important;
  border: 2px solid #333 !important;
  border-radius: 8px;
  overflow: hidden;
  min-width: 280px;
  float: right;
  margin-left: 20px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.2);
}

.invoice-details-table-print-safe td {
  padding: 8px 14px !important;
  border-bottom: 1px dashed #666 !important;
  background: white !important;
}

.invoice-details-table-print-safe tr:last-child td {
  border-bottom: none !important;
}

.invoice-details-table-print-safe .meta-label {
  background: #e6f3ff !important;
  font-weight: 800;
  color: #000 !important;
  width: 115px;
  text-align: left;
}

.invoice-details-table-print-safe .meta-value {
  font-weight: 700;
  color: #000 !important;
  text-align: left;
  padding-left: 12px !important;
}

/* THE MOST IMPORTANT PART - FORCE RENDER IN PDF */
@media print {
  .bill-party-right,
  .invoice-details-table-print-safe,
  .invoice-details-table-print-safe * {
    visibility: visible !important;
    display: table-row !important;
    opacity: 1 !important;
    color: #000 !important;
    background: white !important;
    background-color: white !important;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    float: right !important;
  }

  .invoice-details-table-print-safe {
    background: #f0f8ff !important;
    border: 2px solid #333 !important;
    display: table !important;
  }

  .invoice-details-table-print-safe .meta-label {
    background: #e6f3ff !important;
  }
}

.meta-label {
  font-weight: 700;
  color: #333;
  text-align: left;
  width: 100px;
  white-space: nowrap;
}

.meta-value {
  font-weight: 600;
  color: #000;
  text-align: left;
  padding-left: 8px;
}

.bill-title {
  margin: 0 0 8px 0;
  font-size: 15px;
  font-weight: bold;
  color: #000;
  border-bottom: 1px solid #000;
  display: inline-block;
  padding-bottom: 3px;
}

.text-right {
  text-align: right !important;
}

.mt-4 {
  margin-top: 16px;
}

.party-line {
  margin: 3px 0;
  font-size: 12px;
}
.party-name {
  font-weight: 600;
}

/* Items table */
.tax-invoice-items {
  margin-top: 8px;
}
.items-table {
  width: 100%;
  border-collapse: collapse;
}
.items-table th,
.items-table td {
  border: 1px solid #ddd;
  padding: 4px;
  font-size: 12px;
}
.items-table thead {
  background: #eee;
}
.item-name {
  font-weight: 500;
}
.item-custom-fields {
  margin-top: 2px;
}
.item-custom-field-line {
  display: block;
  font-size: 11px;
  line-height: 1.2;
}

.center {
  text-align: center;
}
.right {
  text-align: right;
}

/* Totals and GST summary */
.tax-invoice-totals {
  margin-top: 6px;
  border-top: 2px dotted #ddd !important;
  border-bottom: 2px dotted #ddd !important;
  padding: 4px 0;
}
.amount-summary-block p {
  margin: 0;
  font-size: 12px;
}
.amount-words {
  margin-top: 4px;
  font-style: italic;
}
.gst-summary-block table {
  width: 100%;
  border-collapse: collapse;
  font-size: 11px;
}
.gst-summary-block th,
.gst-summary-block td {
  border: 1px solid #ddd;
  padding: 3px;
}
.gst-summary-block thead {
  background: #f5f5f5;
}
.gst-summary-total {
  font-weight: 600;
}

/* Paid / Due, footer etc */
.paid-amount-deatils {
  margin-top: 10px;
  text-align: center;
}
.paid-amount-row {
  border-top: 2px dotted #ddd !important;
  border-bottom: 2px dotted #ddd !important;
}
.thanks-details {
  margin-top: 5px;
  text-align: center;
}
.barcode-details {
  margin-top: 10px;
  text-align: center;
}
.footer-button {
  text-align: center !important;
}
.discount-details {
  padding: 5px 0px;
  border-top: 2px dotted #ddd !important;
  border-bottom: 2px dotted #ddd !important;
}
.discount-details p {
  margin-bottom: 0px;
}

/* BANK + TERMS bottom boxed table */
/* =============== FINAL BOTTOM SECTION – EXACTLY LIKE YOUR IMAGE =============== */
/* FINAL PERFECT BOTTOM SECTION – MATCHES YOUR IMAGE 100% */
.bottom-section {
  margin-top: 25px;
  font-size: 13px;
  page-break-inside: avoid;
}

/* 1. BANK DETAILS – ONE CLEAN BOX */
.bank-details-box {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0px;
    border: 2px solid #000;
    padding: 8px 12px;
    background: #fff;
    margin: 25px 0 20px;
    font-size: 11.5px;
    font-weight: 500;
    flex-wrap: wrap;
}
.bank-title {
  font-weight: 900 !important;
  font-size: 15px;
  color: #000;
  min-width: 120px;
  text-align: left;
}

.bank-items {
  display: flex;
  align-items: center;
  gap: 3px;
  flex-wrap: wrap;
  justify-content: center;
  flex: 1;
}

.bank-items span {
  white-space: nowrap;
  font-weight: 500;
}

.separator {
  font-weight: bold;
  color: #000;
  font-size: 16px;
}
/* 2. TWO BOXES BELOW */
.bottom-boxes-row {
  display: flex;
  gap: 20px;
  margin-top: 10px;
}

.terms-box-final,
.signature-box-final {
  flex: 1;
  border: 2.5px solid #000;
  padding: 18px;
  height: 160px;
  position: relative;
  background: white;
}

/* Terms Box */
.terms-header {
  font-weight: bold;
  font-size: 14.5px;
  margin-bottom: 12px;
  text-align: left;
}

.terms-content {
  line-height: 1.7;
  margin-bottom: 30px;
  font-size: 13px;
}

.for-company {
  position: absolute;
  bottom: 18px;
  left: 18px;
  font-weight: bold;
  font-size: 14px;
}

/* Signature Box */
.signature-box-final {
  text-align: center;
}

.signature-title {
  font-weight: bold;
  font-size: 14.5px;
  margin-bottom: 15px;
}

.signature-space {
  height: 85px;
  border-bottom: 2px solid #000;
  margin: 10px 40px;
}

.company-name-bottom {
  margin-top: -12px;
  font-weight: bold;
  font-size: 14px;
}
/* FINAL SINGLE BEAUTIFUL TOTALS BOX */
.final-totals-box {
  margin: 20px 0 25px 0;
  border: 2px solid #000;   /* ← Matches items table exactly */
  background: #fff;
}
.final-totals-box .items-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.final-totals-box .items-table td {
  border: 1px solid #333;
  padding: 8px 10px;
  text-align: left;
}

.final-totals-box .label-strong {
  font-weight: 700;
  background: #f0f0f0;
  width: 18%;
  color: #333;
}

.final-totals-box .value-right {
  text-align: right;
  font-weight: 600;
  background: #fafafa;
}

.final-totals-box .big-total {
  font-size: 16px !important;
  font-weight: 900 !important;
  color: #d00;
  background: #fff0f0 !important;
}

.final-totals-box .paid-strong {
  font-size: 15px;
  color: #0d8321;
  font-weight: 800;
}

.final-totals-box .due-strong {
  font-size: 18px;
  color: #c62828;
  font-weight: 900;
}

/* Mini GST table inside */
.final-totals-box .gst-mini-table th {
  background: #333 !important;
  color: white;
  padding: 7px 5px;
  font-size: 11.5px;
}

.final-totals-box .gst-mini-table td {
  padding: 6px 5px;
  font-size: 11.8px;
}
.final-totals-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13.5px;
}

.final-totals-table td {
  padding: 9px 12px;
  vertical-align: middle;
}

.summary-row {
  background: #f0f0f0;
  font-weight: 600;
}

.label {
  text-align: left;
  width: 18%;
  font-weight: 600;
  color: #333;
}

.value {
  text-align: right;
  width: 15%;
  font-weight: 13px;
}

.big-total {
  font-size: 16px !important;
  font-weight: 900 !important;
  color: #d00;
}

.paid {
  font-size: 15px;
  color: #0d8321;
  font-weight: 800;
}

.due-label {
  background: #ffebee;
  font-size: 16px;
  font-weight: 900;
  color: #c62828;
  text-align: left;
  padding-left: 20px;
}

.due-amount {
  margin-left: 15px;
  font-size: 18px;
  color: #c62828;
}

.words {
  font-style: italic;
  color: #555;
  text-align: right;
  padding-right: 20px;
  font-size: 13px;
}

/* GST Mini Table Inside */
.gst-slab-inside {
  margin: 8px 15px;
  border: 1px solid #000;
  border-radius: 4px;
  overflow: hidden;
}

.gst-mini-table {
  width: 100%;
  font-size: 12px;
  background: white;
}

.gst-mini-table th {
  background: #333;
  color: white;
  padding: 6px;
  font-weight: 600;
  font-size: 11.5px;
}

.gst-mini-table td {
  padding: 5px 8px;
  text-align: center;
}

.gst-mini-table .total-row {
  background: #eee;
  font-weight: bold;
}

.final-row {
  background: #fff8e1;
  border-top: 2px solid #000;
}
.bottom-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
}
.bottom-table td {
  border: 1px solid #000;
  padding: 4px 6px;
  vertical-align: top;
}
.inner-bank-table,
.inner-terms-table {
  width: 100%;
  border-collapse: collapse;
}
.inner-bank-table td,
.inner-terms-table td {
  border: none;
  padding: 2px 0;
}
.bank-header {
  font-weight: 600;
}
.bank-label {
  width: 30%;
}
.bank-value {
  width: 70%;
}
.terms-header {
  font-weight: 600;
  text-align: left;
}
.terms-text-cell {
  text-align: right;
}
.terms-for-cell {
  padding-top: 24px;
  text-align: right;
}
.signature-box {
  padding-top: 30px;
  text-align: center;
}

/* size previews */
.invoice-root {
  width: 100%;
}
.a4-invoice {
  max-width: 210mm;
}
.a5-invoice {
  max-width: 148mm;
}
.thermal-80 {
  max-width: 80mm;
}
.thermal-58 {
  max-width: 58mm;
}
.thermal-80,
.thermal-58 {
  font-size: 12px;
}
@media print {
  @page {
    margin: 0.5cm;
    size: A4; /* or your size */
  }

  body {
    margin: 0;
    padding: 0;
    -webkit-print-color-adjust: exact !important;
    color-adjust: exact !important;
  }

  /* Force background colors (for headers, boxes) */
  .final-totals-box,
  .summary-row,
  .gst-mini-table th,
  .generated-info {
    -webkit-print-color-adjust: exact !important;
    background-color: inherit !important;
  }

  /* Prevent page breaks inside important sections */
  .final-totals-box,
  .bottom-section,
  .bank-details-box,
  .bottom-boxes-row {
    page-break-inside: avoid;
  }

  /* Fix flexbox in print */
  .bottom-boxes-row {
    display: flex !important;
  }
  /* FIX: Right side becomes blank in html2pdf.js → SOLVED! */
@media print {
  .bill-party-right,
  #invoice-details-print,
  .invoice-details-table,
  .invoice-details-table * {
    visibility: visible !important;
    display: table !important;
    opacity: 1 !important;
    color: #000 !important;
    background: white !important;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  
  .bill-party-right {
    float: right !important;
    position: relative !important;
  }
}

.invoice-details-table {
  display: inline-table;
  font-size: 12.5px;
  border: 2px solid #333;
  border-radius: 8px;
  overflow: hidden;
  background: #f0f8ff !important;
  box-shadow: 0 3px 10px rgba(0,0,0,0.2);
  min-width: 260px;
}

.invoice-details-table td {
  padding: 7px 12px;
  border-bottom: 1px dashed #999;
}

.invoice-details-table tr:last-child td {
  border-bottom: none;
}

.meta-label {
  font-weight: 800;
  color: #000;
  background: #e6f3ff;
  width: 110px;
  text-align: left;
  font-size: 12.8px;
}

.meta-value {
  font-weight: 700;
  color: #000;
  text-align: left;
  padding-left: 10px;
  font-size: 13px;
}

/* GSTIN in left side – clean & bold */
.party-line strong {
  font-weight: 800;
  color: #000;
}
.store-contact {
  margin: 6px 0 0 0;
  font-size: 13px;
  line-height: 1.5;
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  justify-content: center;
  align-items: center;
}

.contact-item {
  white-space: nowrap;
}

.gstin-bold {
  font-weight: 600;
}

.gstin-bold strong {
  font-weight: 900;
  color: #000;
  letter-spacing: 0.5px;
}
.final-paid-due-row {
  font-size: 16px !important;
  background: #fff8e1 !important;
}

.paid-due-with-mode {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: 700;
  width: 100%;
}

.paid-part {
  color: #0d8321;
}

.paid-part strong {
  color: #000;
  font-weight: 900;
}

.payment-modes {
  color: #006400;
  font-weight: 800;
  font-size: 15px;
  margin-left: 6px;
}

.due-part {
  color: #c62828;
}

.due-part strong {
  color: #000;
  font-weight: 900;
}

.due-amount {
  font-size: 18px;
  font-weight: 900;
  color: #c62828;
}
}
</style>