<template>
  <a-modal
    :open="visible"
    :centered="true"
    :maskClosable="false"
    :title="$t('common.print_invoice')"
    width="900px"
    @cancel="onClose"
  >
    <div id="pos-invoice">
      <div
        id="pos-invoice-inner"
        :class="['invoice-root', sizeClass]"
        v-if="order && order.xid"
        style="margin: 0 auto"
      >
        <!-- TOP HEADER (STORE INFO) -->
        <div class="invoice-header">
          <img
            class="invoice-logo"
            :src="selectedWarehouse.logo_url"
            :alt="selectedWarehouse.name"
          />
          <div class="invoice-header-text">
            <h1 class="store-name">
              {{ selectedWarehouse.name }}
            </h1>
            <p class="store-address">
              {{ selectedWarehouse.address }}
            </p>
            <p class="store-contact">
              <span v-if="selectedWarehouse.phone">
                {{ $t('common.phone') }}: {{ selectedWarehouse.phone }}
              </span>
              <span v-if="selectedWarehouse.email">
                &nbsp;|&nbsp;{{ $t('common.email') }}: {{ selectedWarehouse.email }}
              </span>
              <!-- GSTN – always show with fallback -->
              <span class="store-gst">
                &nbsp;|&nbsp;GSTIN: {{ displayGSTIN }}
              </span>
            </p>
          </div>
        </div>

        <!-- TAX INVOICE + META (LIKE PDF TOP BOX) -->
        <div class="invoice-meta-row">
          <div class="invoice-meta-left">
            <h2 class="tax-invoice-title">
              {{ $t('sales.tax_invoice') }}
            </h2>
          </div>
          <div class="invoice-meta-right">
            <table class="invoice-meta-table">
              <tbody>
                <tr>
                  <td class="meta-label">
                    {{ $t('sales.invoice') }}
                  </td>
                  <td class="meta-value">
                    : {{ order.invoice_number }}
                  </td>
                </tr>
                <tr>
                  <td class="meta-label">
                    {{ $t('common.date') }}
                  </td>
                  <td class="meta-value">
                    : {{ formatDate(order.order_date) }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- BILL TO (LIKE "BILL TO PARTY" BLOCK) -->
       <div class="bill-party-row">
  <div class="bill-party-left">
    <h3 class="bill-title">Bill To Party</h3>

    <p class="party-line party-name">
      {{ order.user?.name || posSelectedCustomer?.name || 'Walk-in Customer' }}
    </p>

    <p v-if="order.user?.phone || posSelectedCustomer?.phone" class="party-line">
      Mo: {{ order.user?.phone || posSelectedCustomer?.phone }}
    </p>

    <p v-if="order.user?.gst_number" class="party-line">
      GSTN: {{ order.user.gst_number }}
    </p>

    <!-- ADDRESS NOW SHOWS 100% -->
    <p v-if="finalCustomerAddress" class="party-line address-line">
      {{ finalCustomerAddress }}
    </p>
    <p v-else class="party-line text-muted">
      <em>Address not available</em>
    </p>
  </div>

  <div class="bill-party-right">
    <div class="generated-info">
      <p class="party-line"><strong>Generated by:</strong> {{ displayName || 'Admin' }}</p>
      <p class="party-line"><strong>Report Generated At:</strong><br>{{ currentTime }}</p>
    </div>

    <div class="warehouse-location mt-3">
      <p v-if="selectedWarehouse.city" class="party-line">{{ selectedWarehouse.city }}</p>
      <p v-if="selectedWarehouse.state" class="party-line">{{ selectedWarehouse.state }}</p>
    </div>
  </div>
</div>


        <!-- ITEMS TABLE -->
        <div class="tax-invoice-items">
          <table class="items-table">
            <thead>
              <tr>
                <th style="width: 5%">NO</th>
                <th style="width: 25%">{{ $t('common.item') }}</th>
                <th style="width: 10%">{{ 'HSN NO' }}</th>
                <th style="width: 8%">{{ $t('product.unit') }}</th>
                <th style="width: 8%">{{ $t('common.qty') }}</th>
                <th style="width: 12%">{{ $t('common.rate') }}</th>
               
                <th style="width: 8%">{{ $t('product.tax') }} %</th>
                <th style="width: 10%; text-align: right">
                  {{ $t('common.total') }}
                </th>
              </tr>
            </thead>
            <tbody>
              <tr
                class="item-row"
                v-for="(item, index) in order.items"
                :key="item.xid"
              >
                <td class="center">
                  {{ index + 1 }}
                </td>

                <!-- Item name + custom fields (if backend later returns them) -->
                <td>
                  <div class="item-name">
                    {{ item.product?.name }}
                  </div>
                  <div
                    v-if="item.custom_fields && item.custom_fields.length"
                    class="item-custom-fields"
                  >
                    <span
                      v-for="cf in item.custom_fields"
                      :key="cf.id || cf.name || cf.label"
                      class="item-custom-field-line"
                    >
                      {{ cf.label || cf.name }}: {{ cf.value }}
                    </span>
                  </div>
                </td>

                <!-- HSN NO -->
              <td class="center">
  {{ item.hsn_code || item.product?.hsn_code || "-" }}
</td>
<div
  v-if="item.custom_fields && item.custom_fields.length"
  class="item-custom-fields"
>
  <span
    v-for="cf in item.custom_fields"
    :key="cf.id || cf.name || cf.label"
    class="item-custom-field-line"
  >
    {{ cf.label || cf.name }}: {{ cf.value }}
  </span>
</div>

                <!-- UNIT -->
                <td class="center">
                  {{ item.unit?.short_name || item.unit?.name || '-' }}
                </td>

                <!-- QTY -->
                <td class="center">
                  {{ item.quantity }}
                </td>

                <!-- RATE -->
                <td class="right">
                  {{ formatAmountCurrency(item.unit_price) }}
                </td>

             

                <!-- GST % -->
                <td class="center">
                  <span v-if="getTaxRate(item)">
                    {{ getTaxRate(item) }}
                  </span>
                  <span v-else>-</span>
                </td>

                <!-- TOTAL (WITH TAX) -->
                <td class="right">
                  {{ formatAmountCurrency(item.subtotal) }}
                </td>
              </tr>

              <!-- ORDER TAX / DISCOUNT / SHIPPING -->
              <tr class="item-row-other">
                <td colspan="7" class="right">
                  {{ $t('stock.order_tax') }}
                </td>
                <td colspan="2" class="right">
                  {{ formatAmountCurrency(order.tax_amount) }}
                </td>
              </tr>

              <tr class="item-row-other">
                <td colspan="7" class="right">
                  {{ $t('stock.discount') }}
                </td>
                <td colspan="2" class="right">
                  {{ formatAmountCurrency(order.discount) }}
                </td>
              </tr>

              <tr class="item-row-other">
                <td colspan="7" class="right">
                  {{ $t('stock.shipping') }}
                </td>
                <td colspan="2" class="right">
                  {{ formatAmountCurrency(order.shipping) }}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- TOTALS (GROSS / SGST / CGST / IGST / NET) -->
        <div class="tax-invoice-totals">
          <table style="width: 100%">
            <tbody>
              <tr>
                <td style="width: 50%">
                  <div class="amount-summary-block">
                    <p>
                      <strong>GROSS AMT :</strong>
                      {{ formatAmountCurrency(getGrossAmount(order)) }}
                    </p>
                    <p>
                      <strong>SGST :</strong>
                     {{ formatAmountCurrency(computedSGST) }}
                    </p>
                    <p>
                      <strong>CGST :</strong>
                      {{ formatAmountCurrency(computedCGST) }}
                    </p>
                    <p>
                      <strong>IGST :</strong>
                      {{ formatAmountCurrency(computedIGST) }}
                    </p>
                    <p>
                      <strong>NET AMOUNT :</strong>
                      {{ formatAmountCurrency(order.total) }}
                    </p>
                    <p v-if="order.amount_in_words" class="amount-words">
                      Rupees (in words) :- {{ order.amount_in_words }}
                    </p>
                  </div>
                </td>
                <td style="width: 50%">
                  <!-- GST SLAB SUMMARY -->
                  <div class="gst-summary-block">
                    <table>
                      <thead>
                        <tr>
                          <th>GST(%)</th>
                          <th class="right">Taxable</th>
                          <th class="right">GST</th>
                          <th class="right">Net</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr
                          v-for="row in gstSummary"
                          :key="row.rate"
                        >
                          <td class="center">{{ row.rate }}%</td>
                          <td class="right">
                            {{ formatAmountCurrency(row.taxable) }}
                          </td>
                          <td class="right">
                            {{ formatAmountCurrency(row.taxAmount) }}
                          </td>
                          <td class="right">
                            {{ formatAmountCurrency(row.net) }}
                          </td>
                        </tr>
                        <tr class="gst-summary-total">
                          <td class="center">{{ $t('common.total') }}</td>
                          <td class="right">
                            {{ formatAmountCurrency(gstSummaryTotals.taxable) }}
                          </td>
                          <td class="right">
                            {{ formatAmountCurrency(gstSummaryTotals.taxAmount) }}
                          </td>
                          <td class="right">
                            {{ formatAmountCurrency(gstSummaryTotals.net) }}
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- PAID / DUE -->
        <div class="paid-amount-deatils">
          <table style="width: 100%">
            <thead style="background: #eee">
              <tr>
                <td style="width: 50%">
                  {{ $t('payments.paid_amount') }}
                </td>
                <td style="width: 50%">
                  {{ $t('payments.due_amount') }}
                </td>
              </tr>
            </thead>
            <tbody>
              <tr class="paid-amount-row">
                <td>{{ formatAmountCurrency(order.paid_amount) }}</td>
                <td>{{ formatAmountCurrency(order.due_amount) }}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- PAYMENT MODE -->
        <div>
          <table style="width: 100%">
            <tbody>
              <tr style="text-align: center">
                <td style="width: 100%">
                  <h4 style="margin-bottom: 0px" v-if="order.order_payments">
                    {{ $t('invoice.payment_mode') }}:
                    <span
                      v-for="p in order.order_payments"
                      :key="p.xid"
                      style="margin-right: 5px"
                    >
                      {{ formatAmountCurrency(p.amount) }}
                      (<span v-if="p.payment?.payment_mode?.name">
                        {{ p.payment.payment_mode.name }}
                      </span>
                      )
                    </span>
                  </h4>
                  <h3 style="margin-bottom: 0px" v-else>
                    {{ $t('invoice.payment_mode') }}: -
                  </h3>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- DISCOUNT / TAX SUMMARY (OPTIONAL) -->
        <div
          v-if="selectedWarehouse.show_discount_tax_on_invoice"
          class="discount-details"
        >
          <p>
            {{ $t('invoice.total_discount_on_mrp') }} :
            {{ formatAmountCurrency(order.saving_on_mrp) }}
          </p>
          <p>
            {{ $t('invoice.total_discount') }} :
            {{ order.saving_percentage }}%
          </p>
          <p>
            {{ $t('invoice.total_tax') }} :
            {{ formatAmountCurrency(order.total_tax_on_items) }}
          </p>
        </div>

        <!-- BANK DETAIL + TERMS + SIGN – BOX TABLE LIKE PDF -->
        <!-- BOTTOM SECTION – EXACTLY LIKE YOUR IMAGE -->
<!-- BOTTOM SECTION – PERFECT SINGLE BOX BANK DETAILS + TERMS & SIGNATURE -->
<div class="bottom-section">
  <!-- 1. BANK DETAILS – ONE CLEAN HORIZONTAL BOX (LIKE YOUR IMAGE) -->
  <div class="bank-details-box">
    <div class="bank-detail-item"><strong>A/c No :</strong> {{ bankDetailsToShow.accountNo }}</div>
    <div class="bank-detail-item"><strong>Bank :</strong> {{ bankDetailsToShow.bank }}</div>
    <div class="bank-detail-item"><strong>Branch :</strong> {{ bankDetailsToShow.branch }}</div>
    <div class="bank-detail-item"><strong>IFSC :</strong> {{ bankDetailsToShow.ifsc }}</div>
  </div>

  <!-- 2. TWO BOXES BELOW – TERMS + SIGNATURE -->
  <div class="bottom-boxes-row">
    <!-- LEFT: TERMS OF SALES -->
    <div class="terms-box-final">
      <div class="terms-header">Terms Of Sales :</div>
      <div class="terms-content">
        {{ selectedWarehouse.invoice_terms || 'Goods once sold will be taken back or exchanged within 10 Days.' }}
      </div>
      <div class="for-company">
        For : {{ selectedWarehouse.name || 'SHAYONA HANDLOOM & HANDICRAFT' }}
      </div>
    </div>

    <!-- RIGHT: AUTHORISED SIGNATORY -->
    <div class="signature-box-final">
      <div class="signature-title">Authorised Signatory</div>
      <div class="signature-space"></div>
      <div class="company-name-bottom">
        {{ selectedWarehouse.name || 'SHAYONA HANDLOOM & HANDICRAFT' }}
      </div>
    </div>
  </div>
</div>
        <!-- BARCODE / QR + THANKS -->
        <div
          v-if="selectedWarehouse.barcode_type == 'barcode'"
          class="barcode-details"
        >
          <BarcodeGenerator
            :value="order.invoice_number + ''"
            :height="25"
            :width="1"
            :fontSize="15"
            :elementTag="'svg'"
          />
        </div>
        <div v-else style="text-align: center" class="qrcode-details">
          <QRcodeGenerator :text="order.invoice_number + ''" />
        </div>

        <div class="thanks-details">
          <h3>{{ $t('invoice.thanks_message') }}</h3>
          <tr>
 
</tr>

        </div>
      </div>
    </div>

    <template #footer>
      <div class="footer-button">
        <a-button
          v-if="order?.user?.email && isVerified"
          type="primary"
          @click="sendInvoiceMail(order.xid, selectedLang)"
          :loading="isSending"
        >
          <template #icon><SendOutlined /></template>
          {{ $t('common.send_invoice') }}
        </a-button>

        <a-button type="primary" @click="printInvoice">
          <template #icon><PrinterOutlined /></template>
          {{ $t('common.print_invoice') }}
        </a-button>
      </div>
    </template>
  </a-modal>
</template>

<script>
import { ref, defineComponent, onMounted, computed, watch } from "vue";
import { PrinterOutlined, SendOutlined } from "@ant-design/icons-vue";
import common from "../../../../common/composable/common";
import BarcodeGenerator from "../../../../common/components/barcode/BarcodeGenerator.vue";
import QRcodeGenerator from "../../../../common/components/barcode/QRcodeGenerator.vue";
import { notification } from "ant-design-vue";
import { useI18n } from "vue-i18n";

const posInvoiceCssUrl = window.config.pos_invoice_css;

// Static fallbacks (used when warehouse doesn't have data)
const FALLBACK_GSTIN = "24BNGPG0699R1ZD";
const FALLBACK_BANK = {
 
  accountNo: "18650200016691",
  bank: "THE FEDERAL BANK",
  branch: "SURAT VARACHHA",
  ifsc: "FDRL0001865",
};
const authUser = JSON.parse(localStorage.getItem('auth_user')) || {};

// Extract the role and display_name from authUser
const displayName = authUser.name || {};
const currentTime = new Date().toLocaleString();

// Log the display_name in the console
console.log("User Display Name:", displayName);

export default defineComponent({
  props: {
    visible: { type: Boolean, default: false },
    order: { type: Object, default: null },
    size: { type: String, default: "A4" }, // 'A4' | 'A5' | '80mm' | '58mm'
    autoOpen: { type: Boolean, default: false },
  },
  emits: ["closed", "success"],
  components: {
    PrinterOutlined,
    BarcodeGenerator,
    QRcodeGenerator,
    SendOutlined,
  },
  setup(props, { emit }) {
    const { t } = useI18n();
    const {
      formatAmountCurrency,
      formatDate,
      selectedWarehouse,
      selectedLang,
    } = common();

    const isSending = ref(false);
    const isVerified = ref("");

    onMounted(() => {
      axiosAdmin.get("verified-email").then((response) => {
        isVerified.value = response.data?.verified;
      });
    });

    // Debug: log full order/items whenever order changes
    watch(
      () => props.order,
      (o) => {
        if (o) {
          console.log("POS Invoice Order:", JSON.parse(JSON.stringify(o)));
          if (Array.isArray(o.items)) {
            console.log(
              "POS Invoice Order Items:",
              JSON.parse(JSON.stringify(o.items))
            );
          }
        }
      },
      { immediate: true }
    );

    const onClose = () => emit("closed");
const posSelectedCustomer = computed(() => {
      try {
        const raw = localStorage.getItem('pos_selected_customer');
        return raw ? JSON.parse(raw) : null;
      } catch (e) {
        return null;
      }
    });

    // Final customer address to use for GST logic
    const finalCustomerAddress = computed(() => {
      return (props.order?.user?.address || posSelectedCustomer.value?.address || "").trim();
    });

    // Smart Gujarat Detection – Works with "Surat,Gujarat", "Surat Gujarat", "GJ", etc.
    const customerState = computed(() => {
      const addr = finalCustomerAddress.value.toLowerCase();
      const gujaratKeywords = [
        "gujarat", "gujrat", "gj", "surat", "ahmedabad", "vadodara", "rajkot",
        "bhavnagar", "jamnagar", "anand", "gandhinagar", "bharuch", "valsad", "navsari"
      ];
      return gujaratKeywords.some(kw => addr.includes(kw)) ? "Gujarat" : "Other State";
    });

    const isIntraState = computed(() => customerState.value === "Gujarat");

// BEST & MOST ACCURATE METHOD (Recommended)
const totalTaxAmount = computed(() => {
  if (!props.order?.items || !Array.isArray(props.order.items)) return 0;
  
  return props.order.items.reduce((sum, item) => {
    return sum + Number(item.total_tax || 0);
  }, 0);
});
console.log("Total Tax Amount:", totalTaxAmount);
    const computedSGST = computed(() => isIntraState.value ? totalTaxAmount.value / 2 : 0);
    const computedCGST = computed(() => isIntraState.value ? totalTaxAmount.value / 2 : 0);
    const computedIGST = computed(() => isIntraState.value ? 0 : totalTaxAmount.value);
    console.log("SGST:", computedSGST.value);
    console.log("CGST:", computedCGST.value);
    console.log("IGST:", computedIGST.value);
    
    watch(
      () => props.order,
      (newOrder) => {
    if (!newOrder || !newOrder.xid) return;

    const tax = Number(newOrder.tax_amount) || 0;
    const detectedState = customerState.value;
    const isGujarat = detectedState === "Gujarat";

    console.log("════════════════════════════════");
    console.log("GST SPLIT DEBUG (Invoice: %s)", newOrder.invoice_number);
    console.log("Customer Address →", newOrder.user?.address || "N/A");
    console.log("Customer City    →", newOrder.user?.city || "N/A");
    console.log("Detected State   →", detectedState);
    console.log("Is Gujarat?      →", isGujarat ? "YES → SGST + CGST" : "NO → IGST");
    console.log("Total Tax Amount →", tax.toFixed(2));
    console.log("→ SGST           →", computedSGST.value.toFixed(2));
    console.log("→ CGST           →", computedCGST.value.toFixed(2));
    console.log("→ IGST           →", computedIGST.value.toFixed(2));
    console.log("Check Sum        →", (computedSGST.value + computedCGST.value + computedIGST.value).toFixed(2), 
                "==", tax.toFixed(2), 
                (computedSGST.value + computedCGST.value + computedIGST.value) === tax ? "PERFECT" : "ERROR");
    console.log("════════════════════════════════\n");
  },
  { immediate: true }
);

    const sendInvoiceMail = async (xid, lang) => {
      isSending.value = true;
      try {
        await axiosAdmin.get(`send-mail/${xid}/${lang}`);
        notification.success({
          message: t("common.success"),
          description: t("common.mail_sent_successfully"),
          duration: 4.5,
        });
      } catch (error) {
        notification.error({
          message: t("common.error"),
          description: t("common.failed_to_send_mail"),
          duration: 4.5,
        });
      } finally {
        isSending.value = false;
      }
    };

    const sizeClass = computed(() => {
      const s = (props.size || "A4").toUpperCase();
      if (s === "A5") return "a5-invoice";
      if (s === "80MM") return "thermal-80";
      if (s === "58MM") return "thermal-58";
      return "a4-invoice";
    });

    const buildPrintCss = () => {
      const s = (props.size || "A4").toUpperCase();
      if (s === "A5") {
        return `
          @page { size: A5; margin: 10mm; }
          .invoice-root { max-width: 148mm; width: 148mm; }
          body, table { font-size: 12px; }
        `;
      }
      if (s === "80MM") {
        return `
          @page { size: 80mm auto; margin: 5mm; }
          .invoice-root { max-width: 80mm; width: 80mm; }
          body, table { font-size: 11px; }
          .invoice-logo { width: 70px; }
        `;
      }
      if (s === "58MM") {
        return `
          @page { size: 58mm auto; margin: 4mm; }
          .invoice-root { max-width: 58mm; width: 58mm; }
          body, table { font-size: 10px; }
          .invoice-logo { width: 60px; }
        `;
      }
      return `
        @page { size: A4; margin: 12mm; }
        .invoice-root { max-width: 210mm; width: 210mm; }
        body, table { font-size: 13px; }
      `;
    };

    const printInvoice = () => {
      const wrapper = document.getElementById("pos-invoice-inner");
      if (!wrapper) return;
      const invoiceContent = wrapper.outerHTML;
      const newWindow = window.open("", "", "height=800,width=800");
      newWindow.document.write(`
        <html>
          <head>
            <meta charset="utf-8" />
            <link rel="stylesheet" href="${posInvoiceCssUrl}">
            <style>
              ${buildPrintCss()}
              .invoice-header { text-align:center; border-bottom:1px dotted #ddd !important; padding-bottom:4px; }
              .invoice-logo { width:100px; margin-bottom:4px; }
              .store-name { margin:0; font-size:18px; font-weight:700; text-transform:uppercase; }
              .store-address { margin:0; white-space:break-spaces; }
              .store-contact { margin:0; font-size:12px; }
              .invoice-meta-row { margin-top:6px; border-bottom:1px dotted #ddd !important; padding-bottom:4px; display:flex; justify-content:space-between; }
              .tax-invoice-title { margin:0; font-size:16px; font-weight:600; text-transform:uppercase; }
              .items-table { width:100%; border-collapse:collapse; margin-top:8px; }
              .items-table th, .items-table td { border:1px solid #ddd; padding:4px; font-size:12px; }
              .items-table thead { background:#eee; font-weight:600; }
              .right { text-align:right; }
              .center { text-align:center; }
              .tax-invoice-totals { margin-top:6px; border-top:2px dotted #ddd !important; border-bottom:2px dotted #ddd !important; padding:4px 0; }
              .paid-amount-deatils { margin-top:10px; text-align:center; }
              .paid-amount-row { border-top:2px dotted #ddd !important; border-bottom:2px dotted #ddd !important; }
              .thanks-details { margin-top:5px; text-align:center; }
              .barcode-details { margin-top:10px; text-align:center; }
              .discount-details { padding:5px 0px; border-top:2px dotted #ddd !important; border-bottom:2px dotted #ddd !important; }
              .discount-details p { margin-bottom:0px; }

              .bottom-section { margin-top:8px; }
              .bottom-table { width:100%; border-collapse:collapse; font-size:12px; }
              .bottom-table td { border:1px solid #000; padding:4px 6px; vertical-align:top; }
              .inner-bank-table, .inner-terms-table { width:100%; border-collapse:collapse; }
              .inner-bank-table td, .inner-terms-table td { border:none; padding:2px 0; }
              .bank-header { font-weight:600; }
              .terms-header { font-weight:600; text-align:right; }
              .terms-text-cell { text-align:right; }
              .terms-for-cell { padding-top:24px; text-align:right; }
              .signature-box { padding-top:30px; text-align:center; }

              table { width:100%; border-collapse:collapse; }
              thead { background:#eee; }
              @media print {
                table { page-break-inside:auto; }
                tr, td, th { page-break-inside:avoid; }
              }
            </style>
          </head>
          <body>${invoiceContent}</body>
        </html>
      `);
      newWindow.document.close();
      newWindow.focus();
      newWindow.print();
    };

    // Helpers for item-level taxable and tax rate
    const getTaxableAmount = (item) => {
      const subtotal = Number(item.subtotal) || 0;
      const tax =
        Number(item.tax_amount) ||
        Number(item.total_tax) ||
        0;
      const taxable = subtotal - tax;
      return taxable > 0 ? taxable : subtotal;
    };

    const getTaxRate = (item) => {
      if (
        item.tax_rate !== null &&
        item.tax_rate !== undefined &&
        item.tax_rate !== ""
      ) {
        return Number(item.tax_rate);
      }
      const subtotal = Number(item.subtotal) || 0;
      const tax =
        Number(item.tax_amount) ||
        Number(item.total_tax) ||
        0;
      const taxable = subtotal - tax;
      if (taxable > 0 && tax > 0) {
        return Number(((tax / taxable) * 100).toFixed(2));
      }
      return 0;
    };

    const getGrossAmount = (order) => {
      if (order.subtotal) return order.subtotal;
      const total = Number(order.total) || 0;
      const tax = Number(order.tax_amount) || 0;
      const discount = Number(order.discount) || 0;
      const shipping = Number(order.shipping) || 0;
      return total - tax + discount - shipping;
    };

    // GST slab summary from items (group by tax_rate)
    const gstSummary = computed(() => {
      const map = {};
      if (!props.order || !Array.isArray(props.order.items)) return [];

      props.order.items.forEach((item) => {
        const rate = getTaxRate(item) || 0;
        const taxable = getTaxableAmount(item) || 0;
        const tax =
          Number(item.tax_amount) ||
          Number(item.total_tax) ||
          taxable * (rate / 100);

        if (!map[rate]) {
          map[rate] = { rate, taxable: 0, taxAmount: 0, net: 0 };
        }
        map[rate].taxable += taxable;
        map[rate].taxAmount += tax;
        map[rate].net += taxable + tax;
      });

      return Object.values(map).sort((a, b) => a.rate - b.rate);
    });

    const gstSummaryTotals = computed(() => {
      return gstSummary.value.reduce(
        (acc, row) => {
          acc.taxable += row.taxable;
          acc.taxAmount += row.taxAmount;
          acc.net += row.net;
          return acc;
        },
        { taxable: 0, taxAmount: 0, net: 0 }
      );
    });

    // GSTIN + Bank details with static fallback
    const displayGSTIN = computed(() => {
      return selectedWarehouse.gst_number || FALLBACK_GSTIN;
    });

    const bankDetailsToShow = computed(() => {
      return {
        
        accountNo:
          selectedWarehouse.bank_account_no ||
          FALLBACK_BANK.accountNo,
        bank:
          selectedWarehouse.bank_name ||
          FALLBACK_BANK.bank,
        branch:
          selectedWarehouse.bank_branch ||
          FALLBACK_BANK.branch,
        ifsc:
          selectedWarehouse.ifsc_code ||
          FALLBACK_BANK.ifsc,
      };
    });

    watch(
      () => props.visible,
      (v) => {
        if (v && props.autoOpen) {
          setTimeout(() => printInvoice(), 250);
        }
      }
    );

    return {
      onClose,
      formatDate,
      displayName,
      currentTime,
      selectedWarehouse,
      formatAmountCurrency,
      printInvoice,
      selectedLang,
      sendInvoiceMail,
      isSending,
      isVerified,
      sizeClass,
      getTaxableAmount,
      getTaxRate,
      getGrossAmount,
      gstSummary,
      gstSummaryTotals,
      displayGSTIN,
      bankDetailsToShow,
      customerState,
  computedSGST,
  computedCGST,
  computedIGST,
  posSelectedCustomer,
  finalCustomerAddress,
    };
  },
});
</script>

<style>
.invoice-header {
  text-align: center;
  border-bottom: 1px dotted #ddd !important;
  padding-bottom: 6px;
}
.invoice-logo {
  width: 100px;
  margin-bottom: 4px;
}
.invoice-header-text {
  margin-top: 4px;
}
.store-name {
  margin: 0;
  font-size: 18px;
  font-weight: 700;
  text-transform: uppercase;
}
.store-address {
  margin: 0;
  white-space: break-spaces;
}
.store-contact {
  margin: 0;
  font-size: 12px;
}
.store-gst {
  font-weight: 500;
}

.invoice-meta-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-top: 6px;
  border-bottom: 1px dotted #ddd !important;
  padding-bottom: 4px;
}
.tax-invoice-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
}
.invoice-meta-table {
  width: auto;
  font-size: 12px;
}
.invoice-meta-table td {
  padding: 1px 4px;
}
.meta-label {
  font-weight: 500;
  white-space: nowrap;
}
.meta-value {
  white-space: nowrap;
}

/* Bill to party row */
.bill-party-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-top: 10px;
  padding-bottom: 8px;
  border-bottom: 1px dotted #ddd;
}

.bill-party-left {
  flex: 1;
  min-width: 60%;
}
.address-line {
  font-weight: 500;
  margin-top: 4px;
  white-space: pre-line;
}

.generated-info {
  background: #f8f9fa;
  padding: 8px 12px;
  border-radius: 6px;
  border: 1px solid #e0e0e0;
  display: inline-block;
  font-size: 11.5px;
  line-height: 1.4;
}

.bill-party-right {
  flex: 1;
  text-align: right;
  font-size: 11.5px;
  line-height: 1.4;
}

.generated-info {
  background: #f8f9fa;
  padding: 8px 12px;
  border-radius: 4px;
  display: inline-block;
  border: 1px solid #e0e0e0;
}

.text-right {
  text-align: right !important;
}

.mt-4 {
  margin-top: 16px;
}

.party-line {
  margin: 3px 0;
  font-size: 12px;
}
.party-name {
  font-weight: 600;
}

/* Items table */
.tax-invoice-items {
  margin-top: 8px;
}
.items-table {
  width: 100%;
  border-collapse: collapse;
}
.items-table th,
.items-table td {
  border: 1px solid #ddd;
  padding: 4px;
  font-size: 12px;
}
.items-table thead {
  background: #eee;
}
.item-name {
  font-weight: 500;
}
.item-custom-fields {
  margin-top: 2px;
}
.item-custom-field-line {
  display: block;
  font-size: 11px;
  line-height: 1.2;
}

.center {
  text-align: center;
}
.right {
  text-align: right;
}

/* Totals and GST summary */
.tax-invoice-totals {
  margin-top: 6px;
  border-top: 2px dotted #ddd !important;
  border-bottom: 2px dotted #ddd !important;
  padding: 4px 0;
}
.amount-summary-block p {
  margin: 0;
  font-size: 12px;
}
.amount-words {
  margin-top: 4px;
  font-style: italic;
}
.gst-summary-block table {
  width: 100%;
  border-collapse: collapse;
  font-size: 11px;
}
.gst-summary-block th,
.gst-summary-block td {
  border: 1px solid #ddd;
  padding: 3px;
}
.gst-summary-block thead {
  background: #f5f5f5;
}
.gst-summary-total {
  font-weight: 600;
}

/* Paid / Due, footer etc */
.paid-amount-deatils {
  margin-top: 10px;
  text-align: center;
}
.paid-amount-row {
  border-top: 2px dotted #ddd !important;
  border-bottom: 2px dotted #ddd !important;
}
.thanks-details {
  margin-top: 5px;
  text-align: center;
}
.barcode-details {
  margin-top: 10px;
  text-align: center;
}
.footer-button {
  text-align: center !important;
}
.discount-details {
  padding: 5px 0px;
  border-top: 2px dotted #ddd !important;
  border-bottom: 2px dotted #ddd !important;
}
.discount-details p {
  margin-bottom: 0px;
}

/* BANK + TERMS bottom boxed table */
/* =============== FINAL BOTTOM SECTION – EXACTLY LIKE YOUR IMAGE =============== */
/* FINAL PERFECT BOTTOM SECTION – MATCHES YOUR IMAGE 100% */
.bottom-section {
  margin-top: 25px;
  font-size: 13px;
  page-break-inside: avoid;
}

/* 1. BANK DETAILS – ONE CLEAN BOX */
.bank-details-box {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border: 2px solid #000;
  padding: 10px 20px;
  background: #f9f9f9;
  font-weight: 500;
  margin-bottom: 20px;
  border-radius: 4px;
}

.bank-detail-item {
  flex: 1;
  text-align: center;
}

.bank-detail-item strong {
  margin-right: 8px;
  font-weight: 600;
}

/* 2. TWO BOXES BELOW */
.bottom-boxes-row {
  display: flex;
  gap: 20px;
  margin-top: 10px;
}

.terms-box-final,
.signature-box-final {
  flex: 1;
  border: 2.5px solid #000;
  padding: 18px;
  height: 160px;
  position: relative;
  background: white;
}

/* Terms Box */
.terms-header {
  font-weight: bold;
  font-size: 14.5px;
  margin-bottom: 12px;
  text-align: left;
}

.terms-content {
  line-height: 1.7;
  margin-bottom: 30px;
  font-size: 13px;
}

.for-company {
  position: absolute;
  bottom: 18px;
  left: 18px;
  font-weight: bold;
  font-size: 14px;
}

/* Signature Box */
.signature-box-final {
  text-align: center;
}

.signature-title {
  font-weight: bold;
  font-size: 14.5px;
  margin-bottom: 15px;
}

.signature-space {
  height: 85px;
  border-bottom: 2px solid #000;
  margin: 10px 40px;
}

.company-name-bottom {
  margin-top: 12px;
  font-weight: bold;
  font-size: 14px;
}

.bottom-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
}
.bottom-table td {
  border: 1px solid #000;
  padding: 4px 6px;
  vertical-align: top;
}
.inner-bank-table,
.inner-terms-table {
  width: 100%;
  border-collapse: collapse;
}
.inner-bank-table td,
.inner-terms-table td {
  border: none;
  padding: 2px 0;
}
.bank-header {
  font-weight: 600;
}
.bank-label {
  width: 30%;
}
.bank-value {
  width: 70%;
}
.terms-header {
  font-weight: 600;
  text-align: right;
}
.terms-text-cell {
  text-align: right;
}
.terms-for-cell {
  padding-top: 24px;
  text-align: right;
}
.signature-box {
  padding-top: 30px;
  text-align: center;
}

/* size previews */
.invoice-root {
  width: 100%;
}
.a4-invoice {
  max-width: 210mm;
}
.a5-invoice {
  max-width: 148mm;
}
.thermal-80 {
  max-width: 80mm;
}
.thermal-58 {
  max-width: 58mm;
}
.thermal-80,
.thermal-58 {
  font-size: 12px;
}
</style>