<template>
  <a-modal
    :open="visible"
    :centered="true"
    :maskClosable="false"
    :title="$t('common.print_invoice')"
    width="900px"
    @cancel="onClose"
  >
    <div id="pos-invoice">
      <div
        id="pos-invoice-inner"
        :class="['invoice-root', sizeClass]"
        v-if="order && order.xid"
        style="margin: 0 auto"
      >

        <!-- ======================= HEADER ======================= -->
        <div class="invoice-header">
          <h2 class="tax-invoice-title">TAX INVOICE</h2>

          <h1 class="store-name">{{ selectedWarehouse.name }}</h1>

          <p class="store-address">
            {{ selectedWarehouse.address }}
          </p>

          <p class="store-contact-line">
            <span v-if="selectedWarehouse.phone">
              Phone: {{ selectedWarehouse.phone }}
            </span>
            <span v-if="selectedWarehouse.email">
              &nbsp;|&nbsp; Email: {{ selectedWarehouse.email }}
            </span>
          </p>

          <p class="store-gstin-line">
            <strong>GSTIN: {{ displayGSTIN }}</strong>
          </p>
        </div>

        <!-- ======================= BILL TO + INVOICE METADATA ======================= -->
        <div class="bill-party-row">
          
          <!-- LEFT -->
          <div class="bill-party-left">
            <h4 class="bill-title">Bill To Party</h4>

            <p class="party-line party-name">
              {{ order.user?.name || posSelectedCustomer?.name || 'Walk-in Customer' }}
            </p>

            <p class="party-line" v-if="order.user?.phone || posSelectedCustomer?.phone">
              Mo: {{ order.user?.phone || posSelectedCustomer?.phone }}
            </p>

            <p class="party-line" v-if="order.user?.gst_number">
              <strong>GSTIN:</strong> {{ order.user.gst_number }}
            </p>

            <p class="party-line address-line" v-if="finalCustomerAddress">
              {{ finalCustomerAddress }}
            </p>
          </div>

          <!-- RIGHT -->
          <div class="bill-party-right">
            <table class="invoice-details-table">
              <tr>
                <td>Invoice No</td>
                <td>{{ order.invoice_number }}</td>
              </tr>
              <tr>
                <td>Date</td>
                <td>{{ formatDate(order.order_date) }}</td>
              </tr>
              <tr>
                <td>Generated by</td>
                <td>{{ displayName || 'Admin' }}</td>
              </tr>
              <tr>
                <td>Generated at</td>
                <td>{{ currentTime }}</td>
              </tr>
            </table>
          </div>
        </div>

        <!-- ======================= ITEMS TABLE ======================= -->
        <div class="tax-invoice-items">
          <table class="items-table">
            <thead>
              <tr>
                <th style="width: 4%">NO</th>
                <th style="width: 26%">Item</th>
                <th style="width: 10%">HSN NO</th>
                <th style="width: 8%">Unit</th>
                <th style="width: 8%">Qty</th>
                <th style="width: 10%">Rate</th>
                <th style="width: 8%">Tax %</th>
                <th style="width: 12%">Total</th>
              </tr>
            </thead>

            <tbody>
              <tr
                class="item-row"
                v-for="(item, index) in order.items"
                :key="item.xid"
              >
                <td class="center">{{ index + 1 }}</td>

                <td>
                  <div class="item-name">{{ item.product?.name }}</div>
                </td>

                <td class="center">
                  {{ item.hsn_code || item.product?.hsn_code || "-" }}
                </td>

                <td class="center">
                  {{ item.unit?.short_name || item.unit?.name || '-' }}
                </td>

                <td class="center">
                  {{ item.quantity }}
                </td>

                <td class="right">
                  {{ formatAmountCurrency(item.unit_price) }}
                </td>

                <td class="center">
                  {{ getTaxRate(item) || '-' }}
                </td>

                <td class="right">
                  {{ formatAmountCurrency(item.subtotal) }}
                </td>
              </tr>
            </tbody>

          </table>
        </div>

        <!-- ======================= TOTALS TABLE ======================= -->
        <div class="final-totals-box">
          <table class="items-table">

            <tr>
              <td>GROSS AMT:</td>
              <td>{{ formatAmountCurrency(getGrossAmount(order)) }}</td>
              <td>SGST:</td>
              <td>{{ formatAmountCurrency(computedSGST) }}</td>
              <td>CGST:</td>
              <td>{{ formatAmountCurrency(computedCGST) }}</td>
            </tr>

            <tr>
              <td>IGST:</td>
              <td>{{ formatAmountCurrency(computedIGST) }}</td>
              <td>NET AMOUNT:</td>
              <td colspan="3">{{ formatAmountCurrency(order.total) }}</td>
            </tr>

            <tr>
              <td>DUE AMOUNT:</td>
              <td colspan="5" style="color:red;font-weight:bold;">
                {{ formatAmountCurrency(order.due_amount) }}
              </td>
            </tr>

          </table>
        </div>

        <!-- ======================= BANK + TERMS + SIGNATURE ======================= -->
        <div class="bottom-section">

          <div class="bank-details-box">
            <strong>BANK DETAIL:</strong>
            A/c No: {{ bankDetailsToShow.accountNo }} |
            Bank: {{ bankDetailsToShow.bank }} |
            Branch: {{ bankDetailsToShow.branch }} |
            IFSC: {{ bankDetailsToShow.ifsc }}
          </div>

          <div class="bottom-boxes-row">
            <div class="terms-box-final">
              <strong>Terms Of Sales:</strong>
              <p>{{ selectedWarehouse.invoice_terms }}</p>
              <p>For: {{ selectedWarehouse.name }}</p>
            </div>

            <div class="signature-box-final">
              <strong>Authorised Signatory</strong>
              <div class="signature-space"></div>
              <p>{{ selectedWarehouse.name }}</p>
            </div>
          </div>

        </div>

        <!-- ======================= BARCODE / QR ======================= -->
        <div v-if="selectedWarehouse.barcode_type == 'barcode'" class="barcode-details">
          <BarcodeGenerator
            :value="order.invoice_number + ''"
            :height="25"
            :width="1"
            :fontSize="15"
            :elementTag="'svg'"
          />
        </div>

        <div v-else class="qrcode-details" style="text-align: center;">
          <QRcodeGenerator :text="order.invoice_number + ''" />
        </div>

        <!-- ======================= THANK YOU ======================= -->
        <div class="thanks-details">
          <h3>{{ $t('invoice.thanks_message') }}</h3>
        </div>

      </div>
    </div>

    <template #footer>
      <div class="footer-button">
        <a-button v-if="order?.user?.email && isVerified" type="primary" @click="sendInvoiceMail(order.xid, selectedLang)" :loading="isSending">
          <template #icon><SendOutlined /></template>
          {{ $t('common.send_invoice') }}
        </a-button>

        <a-button type="default" @click="downloadPdf" style="margin-right: 8px;">
          <template #icon><DownloadOutlined /></template>
          Download PDF
        </a-button>

        <a-button type="primary" @click="printInvoice">
          <template #icon><PrinterOutlined /></template>
          {{ $t('common.print_invoice') }}
        </a-button>
      </div>
    </template>

  </a-modal>
</template>
